refactor: use aerial to provide outline.
ayamir/nvimdots pull request #1059
Opened 2023-11-09 03:04 UTC by ayamir

[Aerial.nvim](https://github.com/stevearc/aerial.nvim) has better outline support than [symbols-outline.nvim](https://github.com/simrat39/symbols-outline.nvim). #1058 will be solved.

2023-11-09 03:05 UTC, ayamir commented
![image](https://github.com/ayamir/nvimdots/assets/61657399/f3819bdd-b417-45eb-ab03-b986335627e3)

![1699499087151](https://github.com/ayamir/nvimdots/assets/61657399/6e7b370b-1882-498f-9b71-47ca901dc7f2)

2023-11-09 03:30 UTC, CharlesChiuGit requested changes

2023-11-09 03:30 UTC, CharlesChiuGit commented on lua/modules/configs/completion/aerial.lua
> +			"Struct",
I think it's too few symbols for default usage, maybe add all symbols first?
```
Array
Boolean
Class
Constant
Constructor
Enum
EnumMember
Event
Field
File
Function
Interface
Key
Method
Module
Namespace
Null
Number
Object
Operator
Package
Property
String
Struct
TypeParameter
Variable
```

2023-11-09 03:38 UTC, CharlesChiuGit commented on lua/modules/configs/completion/aerial.lua
> +			"Struct",
before
![image](https://github.com/ayamir/nvimdots/assets/32497323/6d595d74-fac4-4dfb-835a-64f6c3e1f7b0)

after
![image](https://github.com/ayamir/nvimdots/assets/32497323/c5efd3aa-8c0a-4621-9c4c-1836c5ec9a2a)

2023-11-09 03:44 UTC, CharlesChiuGit commented
also the keymaps doesn't seem working.

2023-11-09 04:00 UTC, CharlesChiuGit commented
also i think `aerial`'s telescope extension is so spot on that I think we should just change `go` to open the telescope preview.
How do u think? @ayamir @Jint-lzxy

2023-11-09 06:33 UTC, Jint-lzxy commented
> also i think `aerial`'s telescope extension is so spot on that I think we should just change keymap:`go` to open it's telescope preview. How do u think?

Agree, but why not assign a keymap to each of them lol

2023-11-09 06:37 UTC, CharlesChiuGit commented
> Agree, but why not assign a keymap to each of them lol

absolutely! that would be nice too!

2023-11-09 07:44 UTC, CharlesChiuGit approved these changes

2023-11-09 09:03 UTC, CharlesChiuGit commented
I think it gd to go.

2023-11-09 09:20 UTC, Jint-lzxy commented
Sorry I'm a bit busy with other stuff atm. I'll review this PR sometime tomorrow :D

2023-11-09 15:07 UTC, CharlesChiuGit approved these changes
LGTM

2023-11-10 15:29 UTC, Jint-lzxy approved these changes
LGTM 🍯 but we probably need to update the relevant parts of the wiki before merging this lol

2023-11-11 06:42 UTC, merged