Use Nerd Font to replace the +prefix (It's just a demo)
ayamir/nvimdots pull request #1134
Opened 2024-01-07 14:40 UTC by Cyberczy

2024-01-08 12:39 UTC, ayamir commented
IMO it's better to register prefix for `which-key` when the keymappings are binded, i.e., invoking the `bind.nvim_load_mapping`.

2024-01-08 12:41 UTC, Cyberczy commented
It's up to you. I'm just making a suggestion.

2024-01-11 15:52 UTC, Cheny-chui commented
I have made some improvements to this pr based on ayamir's suggestion, can you please give me modification access to this pr? @Cyberczy (I'm not sure if I need your action, but I really can't push to your repository). Or maybe need the maintainer's action @ayamir .

2024-01-11 15:58 UTC, Cyberczy commented
> 我根据ayamir的建议对这个pr做了一些改进，你能给我这个pr的修改权限吗？@Cyberczy（我不确定是否需要您的操作，但我确实无法自动到达您的存储库）。或者可能维护者的操作@ayamir。

I don't have the authority, lol

2024-01-12 02:04 UTC, ayamir commented
It seems better that @Cyberczy give the authority of your fork to @Cheny-chui as the GitHub Docs says: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

2024-01-12 04:07 UTC, Cyberczy commented
Ok, I've just given you modification access. @Cheny-chui

2024-01-12 07:35 UTC, ayamir commented
@CharlesChiuGit Could you please review this PR?

2024-01-12 08:54 UTC, CharlesChiuGit commented
ok, let me take a look.

2024-01-12 09:14 UTC, CharlesChiuGit requested changes
plz remove lazy-lock

2024-01-12 09:14 UTC, CharlesChiuGit commented on lazy-lock.json
please remove lazy-lock

2024-01-12 10:06 UTC, Cyberczy commented on lazy-lock.json
ok

2024-01-12 13:34 UTC, ayamir commented
Current prefix settings is not enough and need to be added manually. I'm thinking automatically setting whether is a better idea. Though this requires keymap setup to keep align with it.

Additionally, maybe we can refactor current keymap settings through this PR, such as:
`<leader>D` -> `<leader>hd`
`<leader><leader>D` -> `<leader>hD`
What do you think? @CharlesChiuGit @Jint-lzxy

2024-01-14 19:14 UTC, vabatta commented
What is the general rationale behind the current key mapping?
Is it quick commands, frequent commands or "grouped" commands (like [LazyVim](https://www.lazyvim.org/keymaps) which maps into groups like `<leader>w` for windows, `<leader>b` for buffers, ...)?

2024-01-15 03:36 UTC, CharlesChiuGit submitted a review, later dismissed

2024-01-15 09:30 UTC, ayamir commented
> What is the general rationale behind the current key mapping? Is it quick commands, frequent commands or "grouped" commands (like [LazyVim](https://www.lazyvim.org/keymaps) which maps into groups like `<leader>w` for windows, `<leader>b` for buffers, ...)?

Current keymap settings are mixed but a little confusing due to history reasons.

2024-01-15 09:41 UTC, CharlesChiuGit commented
```lua
--- Need to expand by hand
local prefix_desc = {
	["<leader>b"] = icons.ui_sep.Buffer .. "Buffer",
	["<leader>c"] = icons.ui_sep.Character .. "Character",
	["<leader>d"] = icons.ui_sep.Bug .. "Debug",
	["<leader>f"] = icons.ui_sep.Telescope .. "Fuzzy Find",
	["<leader>h"] = icons.ui_sep.Git .. "Git Hunk",
	["<leader>l"] = icons.ui_sep.Lsp .. "Lsp",
	["<leader>p"] = icons.ui_sep.Package .. "Package",
	["<leader>n"] = icons.ui_sep.FolderOpen .. "Nvim Tree",
	["<leader>s"] = icons.ui_sep.Tmux .. "Session",
	["<leader>t"] = icons.ui_sep.Lsp .. "Lsp",
	["<leader><space>"] = icons.ui_sep.Git .. "Git: Close diff",
}
```
After pressing leader key one time, some prefix still can be shown, hmmm.
![image](https://github.com/ayamir/nvimdots/assets/32497323/9d1867c6-222c-43cf-8901-964e02fc876a)

2024-01-15 09:48 UTC, Cyberczy commented
> `lua\keymap\prefix.lua`
> 
> ```lua
> --- Need to expand by hand
> local prefix_desc = {
> 	["<leader>b"] = icons.ui_sep.Buffer .. "Buffer",
> 	["<leader>c"] = icons.ui_sep.Character .. "Character",
> 	["<leader>d"] = icons.ui_sep.Bug .. "Debug",
> 	["<leader>f"] = icons.ui_sep.Telescope .. "Fuzzy Find",
> 	["<leader>h"] = icons.ui_sep.Git .. "Git Hunk",
> 	["<leader>l"] = icons.ui_sep.Lsp .. "Lsp",
> 	["<leader>p"] = icons.ui_sep.Package .. "Package",
> 	["<leader>n"] = icons.ui_sep.FolderOpen .. "Nvim Tree",
> 	["<leader>s"] = icons.ui_sep.Tmux .. "Session",
> 	["<leader>t"] = icons.ui_sep.Lsp .. "Lsp",
> 	["<leader><space>"] = icons.ui_sep.Git .. "Git: Close diff",
> }
> ```
> 
> 按一次leader键后，仍然可以显示一些前缀，嗯。 ![图像](https://private-user-images.githubusercontent.com/32497323/296714609-9d1867c6-222c-43cf-8901-964e02fc876a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTIwNDUsIm5iZiI6MTcwNTMxMTc0NSwicGF0aCI6Ii8zMjQ5NzMyMy8yOTY3MTQ2MDktOWQxODY3YzYtMjIyYy00M2NmLTg5MDEtOTY0ZTAyZmM4NzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5NDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NmVjNzEzOTk1YWNmZGRiMjlmMDI5YzY0ZTE4MjhiZTBmZDI3MTExYzBhMjBhZTExNjM1NTgxYTg1N2ViYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sUFtQkG5iQqSD6j5TZUlAuihEoTfa1t1DECfLZp8YeM)


`<leader><space>` seems to have no effect.

2024-01-15 10:03 UTC, CharlesChiuGit commented
> `<leader><space>` seems to have no effect.

yeah, im not sure how to set it. i have tried `<leader><space>` or `<leader><leader>` both r not working.
also, `<leader>h` and `<leader>l` r not valid too.

2024-01-15 10:17 UTC, CharlesChiuGit commented
@ayamir @Jint-lzxy 
since our keymap group is a bit confusing right now, our which-key prefix nerdfont hit might be a bit misleading too.

2024-01-15 11:33 UTC, ayamir commented
IMO it's better to refactor it.

2024-01-17 08:34 UTC, ayamir commented
It looks tidy now.
![image](https://github.com/ayamir/nvimdots/assets/61657399/5eca9f39-e021-4086-ad5e-6a7e7fbde540)

2024-01-17 08:35 UTC, Cyberczy commented
LGTM!!!

2024-01-17 08:58 UTC, Cyberczy commented
The right half of which-key seems a bit empty. Perhaps we can add a bit of padding.

2024-01-17 14:55 UTC, ayamir commented
> The right half of which-key seems a bit empty. Perhaps we can add a bit of padding.

IMO it is unnecessary.

2024-01-17 14:57 UTC, Cyberczy commented
> > The right half of which-key seems a bit empty. Perhaps we can add a bit of padding.
> 
> IMO it is unnecessary.

Alright, it's just a suggestion

2024-01-17 15:22 UTC, Jint-lzxy commented
Sorry for the delay! My sched's been a bit tight recently. But I'll probably review this in the next day or two lol

2024-01-18 06:09 UTC, CharlesChiuGit approved these changes
LGTM

2024-01-19 14:35 UTC, Jint-lzxy approved these changes
LGTM! This PR is awesome lmao
***
(idk if this is related) But I'm wondering if the real issue might lie in the implementation of [which-key.nvim](https://github.com/folke/which-key.nvim), as I used a [different approach](https://github.com/Jint-lzxy/nvimconfig/blob/f5e4e72cb7ab884c7afef4274c64a991ad850713/lua/modules/configs/tool/which-key.lua#L33) to handle keymap registration, but it seems that (only recently) which-key sometimes displays `+prefix` even for named groups (like `<leader>h`, see the screenshot below):
<img width="811" alt="S" src="https://github.com/ayamir/nvimdots/assets/50296129/5d214f98-45f3-4287-adf2-418367cd4827">

Then I did a git bisect, and the issue seems to originate from [this commit](https://github.com/folke/which-key.nvim/commit/8503c0d725420b37ac31e44753657cde91435597) (strangely tho, this means that which-key thinks some of my keymap groups don't have a valid name, but obviously I _did_ give them names). For some reason, in [this call](https://github.com/folke/which-key.nvim/blob/4433e5ec9a507e5097571ed55c02ea9658fb268a/lua/which-key/keys.lua#L116), the (to be processed) group still has a name, but immediately [in the next line](https://github.com/folke/which-key.nvim/blob/4433e5ec9a507e5097571ed55c02ea9658fb268a/lua/which-key/keys.lua#L117), that name disappears. Based on this, IMO a simpler solution 'might' be to revert [`8503c0`](https://github.com/folke/which-key.nvim/commit/8503c0d725420b37ac31e44753657cde91435597) (I can create a fork just like we made a temporary fix for `lsp-signature`), and then wait for folke's response (I'll open an issue for this); or just merge this PR. What do you guys think @ayamir @CharlesChiuGit?

2024-01-20 10:03 UTC, ayamir commented
Made improvement for startup time.
Before: 
![image](https://github.com/ayamir/nvimdots/assets/61657399/1f2fe996-eca4-4de3-9393-e3c6c6a5229b)
Now:
![image](https://github.com/ayamir/nvimdots/assets/61657399/79639635-44e3-476a-abac-11c000c5105b)

2024-01-20 10:19 UTC, ayamir commented
> (idk if this is related) But I'm wondering if the real issue might lie in the implementation of [which-key.nvim](https://github.com/folke/which-key.nvim), as I used a [different approach](https://github.com/Jint-lzxy/nvimconfig/blob/f5e4e72cb7ab884c7afef4274c64a991ad850713/lua/modules/configs/tool/which-key.lua#L33) to handle keymap registration, but it seems that (only recently) which-key sometimes displays `+prefix` even for named groups (like `<leader>h`, see the screenshot below): <img alt="S" width="811" src="https://private-user-images.githubusercontent.com/50296129/298094637-5d214f98-45f3-4287-adf2-418367cd4827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDMxNDksIm5iZiI6MTcwNTc0Mjg0OSwicGF0aCI6Ii81MDI5NjEyOS8yOTgwOTQ2MzctNWQyMTRmOTgtNDVmMy00Mjg3LWFkZjItNDE4MzY3Y2Q0ODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA5MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YjkwMzVmZTA0ZDk5ZDNjYjNiNjFkNTI0NmNkNWRmMTE4MzQyNTVjNGJiODk0ZDJiYjM5ZDUxMjNhMWFmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v4oxUY9RrfOUHb1zNVX2G9KTYQFATg_xIzdh3hOpVkM">

I didn't view settings about `<leader>h` for group name in https://github.com/Jint-lzxy/nvimconfig/blob/f5e4e72cb7ab884c7afef4274c64a991ad850713/lua/modules/configs/tool/which-key.lua#L34-L145

2024-01-21 12:16 UTC, Jint-lzxy commented
> I didn't view settings about `<leader>h` for group name ...

Ah, I think this probably isn't related. Sorry for the noise here! (I didn't notice that our impl is kinda like an event loop 🙈) Here's a similar issue with more details: https://github.com/folke/which-key.nvim/issues/482.

@ayamir With that being said, I'm still a bit puzzled as to why we need to register these mappings dynamically. I feel like just statically registering them using `require("which-key").register({})` would be enough, since `which-key` should do the grouping work (correct me if I'm misunderstanding something lmao). Registering a callback that gets invoked every 300 milliseconds seems a bit inefficient to me.

2024-01-21 13:14 UTC, ayamir commented
> With that being said, I'm still a bit puzzled as to why we need to register these mappings dynamically. I feel like just statically registering them using require("which-key").register({}) would be enough, since which-key should do the grouping work (correct me if I'm misunderstanding something lmao).

It's b/c the statical way only register the group name once when init and doesn't work for our lsp-related keymaps are binded with buffer after `LspAttach` event. But after the keymap refactored, this problem is addressed now (b/c `trouble.nvim`-related keymaps were merged into the `<leader>l` group). Indeed, now we can use the statical way to avoid unnecessary complexity lol.
![image](https://github.com/ayamir/nvimdots/assets/61657399/7f574def-11f7-4c82-85fa-6de5cfc3c321)

2024-01-22 12:00 UTC, Cyberczy commented
So, should we stick with statically registering them, or should we maintain the current state by dynamically registering them?

2024-01-22 15:12 UTC, ayamir approved these changes

2024-01-22 15:12 UTC, merged