Add some new plugins
ayamir/nvimdots pull request #1235
Opened 2024-04-19 11:36 UTC by CharlesChiuGit

1. [advanced-git-search.nvim](https://github.com/aaronhallaert/advanced-git-search.nvim)
2. [search.nvim](https://github.com/FabianWirth/search.nvim)
3. ...

2024-04-20 02:53 UTC, ayamir approved these changes
LGTM

2024-04-20 03:55 UTC, CharlesChiuGit commented
do i need to change the target branch to 0.10? @ayamir

2024-04-20 05:07 UTC, ayamir commented
> do i need to change the target branch to 0.10? @ayamir

it's better to switch 👍

2024-04-20 10:32 UTC, Jint-lzxy commented on lua/keymap/tool.lua
> +---@diagnostic disable: undefined-field
```suggestion
```

I think we could possibly remove those lines suppressing diagnostics and instead add `undefined-field` to [`Lua.diagnostics.disable`](https://github.com/ayamir/nvimdots/blob/8268d2768222c9ff37114cb59524cfa44a3f2f7a/lua/modules/configs/completion/servers/lua_ls.lua#L7)? Personally, I don't find it particularly useful since this one tends to produce a bunch of false-positives.

2024-04-20 10:56 UTC, ayamir commented on lua/keymap/tool.lua
> +---@diagnostic disable: undefined-field
Agree.

2024-04-28 07:06 UTC, gezhanling commented
May you consider add the **vim-orgmode** plugin?

2024-04-28 09:49 UTC, CharlesChiuGit commented
i'm not if adding orgmode would benefit most neovim users. 
If we really need to add orgmode, i think https://github.com/nvim-orgmode/orgmode would be better.

2024-04-30 09:23 UTC, Jint-lzxy commented
> if adding orgmode would benefit most neovim users.

If memory serves me correctly, I think this is exactly why we dropped orgmode around two years ago. It's undeniably powerful, but getting the hang of it still demands some effort. Plus IMHO it actually diverges from the primary purpose of using neovim as _a_ pure text editor for the _majority_ of neovim users - its code is notably self-contained and straightforward to configure, but it's also massive(!), which (I think) categorizes it as an excellent example of custom plugins rather than being included in our default plugin list. My two cents on using orgmode is that it's a great "app" for note-taking related stuff, but it's definitely not a must-have for our base config.

2024-05-09 02:57 UTC, gezhanling commented
> My two cents on using orgmode is that it's a great "app" for note-taking related stuff

By the way, do you use the Emacs orginal orgmode?

2024-05-13 04:46 UTC, Jint-lzxy commented
> > My two cents on using orgmode is that it's a great "app" for note-taking related stuff
> 
> By the way, do you use the Emacs orginal orgmode?

@gezhanling I experimented with that years ago before transitioning to Vim, and imo it worked nicely with Emacs :D

2024-06-09 13:04 UTC, Jint-lzxy requested changes
I only gave these plugins' descriptions a quick once-over, so plz correct me if I'm wrong!

2024-06-09 13:04 UTC, Jint-lzxy commented on lua/modules/configs/editor/highlight-colors.lua
> +		enable_named_colors = false,
I recall NvChad's version having a similar option that's enabled by default. Should we enable it here as well? (Personally, I don't find it particularly useful tho)

2024-06-09 13:04 UTC, Jint-lzxy commented on lua/modules/plugins/tool.lua
> +		},
What's the specific use case for this plugin? I thought fugitive could handle all those tasks.

2024-06-09 13:04 UTC, Jint-lzxy commented on lua/modules/plugins/tool.lua
> +		},
Great plugin! But can we streamline it by assigning just one "meta key" to all Telescope search commands, instead of leaving some of them outside (like [telescope-undo](https://github.com/debugloop/telescope-undo.nvim))?

2024-06-11 02:32 UTC, CharlesChiuGit commented on lua/modules/configs/editor/highlight-colors.lua
> +		enable_named_colors = false,
yeah, i dont think highlighting named colors are not so useful and will cause disruption when I need to write things in markdown or code descriptions, so i set it to false by default.

2024-06-11 02:34 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
it can be integrated w/ telescope and use fuzzy search for commits and so on. i think it's a nice to have.

2024-06-11 02:37 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
It could also be integrated w/ `search.nvim` to empower greater use.

2024-06-11 03:07 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
i don't quite get this, could u explain more?
Isn't all telescope search keymaps start w/ `<leader>f{X}` now?

2024-06-11 07:43 UTC, CharlesChiuGit commented
aha, totally forget to change that lol. 
tks for the fix up!

2024-06-11 07:47 UTC, Jint-lzxy commented on lua/modules/plugins/tool.lua
> +		},
lol I almost forgot about real-time fuzzy searching! Initially, I thought this plugin might be covered by [Advanced Searching Techniques _«Pro Git»_](https://git-scm.com/book/en/v2/Git-Tools-Searching). Thanks for the heads up!

2024-06-11 07:56 UTC, Jint-lzxy commented on lua/modules/plugins/tool.lua
> +		},
Sure thing! I mean can we consolidate all Telescope commands just under a single key, such as `<leader>f`, for all actions (like invoking `require("search").open({ collection = "all" })`, instead of organizing them into subgroups, such as `collection = "git"`, within map groups like `<leader>fg`? But I'm okay with the current approach too lol

2024-06-11 07:58 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
i don't know those advanced git searching techniques! TIL!

2024-06-13 08:32 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
after some research, a meta key to open all collections seems undoable, but i will add some more collections to make things more organized.

2024-06-13 11:06 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
i kinda solved this problem, but i hard-coded it: https://github.com/ayamir/nvimdots/blob/400e77d977c0a5d5da04194a2aa82d09d536cd0e/lua/keymap/helpers.lua#L22

i'm not sure if there's any way to get table elements in another function.

2024-06-13 11:07 UTC, CharlesChiuGit commented
hmmm, i'm not sure why `luacheck` didn't pass.

2024-06-14 01:45 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
![image](https://github.com/ayamir/nvimdots/assets/32497323/433e8a1d-0ca9-470d-bd32-bbf91335a694)

2024-06-14 02:37 UTC, CharlesChiuGit commented
I set https://github.com/ayamir/nvimdots/blob/400e77d977c0a5d5da04194a2aa82d09d536cd0e/lua/modules/configs/tool/search.lua#L4 to default setup instead our custom setup function since it might cause issue for current universal telescope collections panel.

2024-06-14 03:56 UTC, Jint-lzxy commented
I'm a bit occupied right now, but I'll check out this PR later this week lol

2024-06-16 16:41 UTC, Jint-lzxy commented on lua/modules/plugins/tool.lua
> +		},
> i'm not sure if there's any way to get table elements in another function.

A quick glance at the doc seems to suggest it's doable, but we might need some of Telescope's API to make it work. Specifically, the `exports` table in the extensions API (tho I might be wrong about the name lol). I think I can work on this over the next few days.

2024-06-16 16:46 UTC, Jint-lzxy commented on lua/modules/plugins/tool.lua
> +		},
> ![image](https://private-user-images.githubusercontent.com/32497323/339601788-433e8a1d-0ca9-470d-bd32-bbf91335a694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTU3NDcsIm5iZiI6MTcxODU1NTQ0NywicGF0aCI6Ii8zMjQ5NzMyMy8zMzk2MDE3ODgtNDMzZThhMWQtMGNhOS00NzBkLWJkMzItYmJmOTEzMzVhNjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE2MzA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YWIxY2Y5Mzk3ODZmMmI3YmQ1ZDY0ZGYyYTdiZjkzMDRhMjFlM2RmZTQyMmIwZTc5ODIyNjhlOTg0NTYyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tYXbCAQaKaYaHD-_PLtrEl41JdeT7sPovnEnASiCvJQ)

btw, just spotted a typo in the header: `Telesscope -> Telescope` u must be an expert typist to type that fast 😂

2024-06-17 03:39 UTC, CharlesChiuGit commented on lua/modules/plugins/tool.lua
> +		},
lol fixed that typo.

> u must be an expert typist to type that fast 😂

maybe just fat fingers lol

2024-06-17 09:08 UTC, Jint-lzxy commented
> ... to default setup instead our custom setup function since it might cause issue for current universal telescope collections panel.

@CharlesChiuGit I've tried my best to comprehend this PR, but I'm still a bit perplexed about the current implementation. iiuc we have five different search groups for Telescope (namely `file`, `live_grep`, `git`, `workspace` and `misc`). However, in `lua/keymap/tool.lua`, I only see two of these groups (`file` and `git`) being actively used, not including the "mega" key `<leader>f`. Is there a specific design reason for this, or did I miss something?

2024-06-17 09:17 UTC, CharlesChiuGit commented
tbh, i think we can remove those keymaps and just keep the <leader>f, i leave <leader>fX there just to keep consistent w/ our old config, so we won't be bombarded w/ issues lol

2024-06-17 09:19 UTC, CharlesChiuGit commented
ohno, i see your point.
i forgot to add it!

2024-06-17 09:50 UTC, Jint-lzxy commented
> isn't this what u mean by mega key?

Exactly! We probably just need to invoke [`TabCollection:all()`](https://github.com/FabianWirth/search.nvim/blob/7b8f2315d031be73e14bc2d82386dfac15952614/lua/search/tabs/collection.lua#L24-L26) to get this then. Easy peasy lmao!

2024-06-17 10:10 UTC, CharlesChiuGit commented
https://github.com/ayamir/nvimdots/blob/3d77f4abcf81f788bccdb322218b137fb855b9f5/lua/core/mapping.lua#L41

i move `<leader>bn` to `core/mapping.lua` since i don't see a reason to leave it under `telescope` lol

2024-06-17 10:23 UTC, Jint-lzxy commented
WAM I think with the current state of the PR, we also need to update [dots.tutor](https://github.com/ayamir/nvimdots/blob/a04cb81f1c20db8334447a8433b24a34ac3aa0a2/tutor/dots.tutor#L86-L113) (Lesson 1.2) ┬─┬ノ( º _ ºノ)

2024-06-17 10:31 UTC, Jint-lzxy commented
@CharlesChiuGit Would u mind undertaking the illustrious yet arduous endeavor of updating both the wiki and `dots.tutor`, or shall we divide the tasks and complete them collaboratively? tbf I'm finding myself oddly fatigued given the current situation 🤣

***

<p align="center">
  <img src="https://i.kym-cdn.com/photos/images/original/000/900/481/9de.gif" />
</p>

2024-06-17 10:55 UTC, CharlesChiuGit commented
sure! i can update the wiki part lol
take your time! rest as u need

2024-06-17 11:24 UTC, Jint-lzxy commented
> sure! i can update the wiki part lol

🫡Thanks a ton! btw I used to use this one-liner (after cloning our repo's wiki pages `git clone https://github.com/ayamir/nvimdots.wiki.git`)
```console
$ awk '/^\|/{ print $(NF-1) }' < Keybindings.md | sed -e '/^`/!d' -e 's/^`\(.*\)`$/\1/g'
```
to retrieve the list of possible keymaps. However, that page hasn't been updated in a long time, so u might need to put in some extra effort to ensure all the entries are valid 😆 

(Just came up with the following to retrieve the list of defined keymaps in our config. I haven't tested it thoroughly though, but it should work fine :D)

```console
$ rg -IN '\s*\[".*?\|(.*?)"\] = .*$' -r '$1' | sed '/^$/d'
```

> take your time! rest as u need

nvm I'm just joking after seeing the potential paperwork lol I'll take care of `dots.tutor`, but I might need ur input to ensure everything aligns correctly with respect to `search.nvim` XD

2024-06-18 03:31 UTC, CharlesChiuGit commented
i think we can merge this pr and update tutor and wiki later?

2024-06-18 03:52 UTC, Jint-lzxy reviewed
Holy crap I somehow forgot to submit the review for this yesterday lol

2024-06-18 03:52 UTC, Jint-lzxy commented on lua/modules/configs/tool/search.lua
> +	require("search").setup({
```suggestion
	require("modules.utils").load_plugin("search", {
```

I think our custom loader should come in handy here now 😂

2024-06-18 03:56 UTC, CharlesChiuGit commented on lua/modules/configs/tool/search.lua
> +	require("search").setup({
wow, sorry i don't know i can just sign off suggestion changes!

2024-06-18 03:57 UTC, Jint-lzxy commented
> i think we can merge this pr and update tutor and wiki later?

Sure! ur PR, ur choice lol (But I'll try to fix the checks tho)

2024-06-18 04:01 UTC, Jint-lzxy commented on lua/modules/configs/tool/search.lua
> +	require("search").setup({
> wow, sorry i don't know i can just sign off suggestion changes!

nvm I didn't know that either until I saw a repo's maintainer submit my suggestions in less than a second (\*hyperbole). I was like 🤯 🤣

2024-06-18 04:43 UTC, Jint-lzxy approved these changes
LGTM

2024-06-18 05:39 UTC, merged

2024-06-18 14:34 UTC, ayamir commented
Sorry for the late reply, currently I'm busy with internship work so I have little time to participate in discussions.
IMO current `Telescope Collections` as a middle selector may hinder fast operation and break the workflow. Perhaps it would be more acceptable to users to keep the key bindings that can directly open different search category interfaces.
In addition, we also need to modify the alpha-nvim UI for the new key bindings

2024-06-19 03:18 UTC, CharlesChiuGit commented
> Sorry for the late reply, currently I'm busy with internship work so I have little time to participate in discussions. IMO current `Telescope Collections` as a middle selector may hinder fast operation and break the workflow. Perhaps it would be more acceptable to users to keep the key bindings that can directly open different search category interfaces. For example, use `<leader>ff` can open the `file` tab directly. In addition, we also need to modify the alpha-nvim UI for the new key bindings

ok, will do

2024-06-19 05:22 UTC, Jint-lzxy commented
> Sorry for the late reply, currently I'm busy with internship work so I have little time to participate in discussions.

And best of luck with ur internship lol!