Fix/nixos
ayamir/nvimdots pull request #1250
Opened 2024-04-29 16:34 UTC by misumisumi

Regarding the previous PR, I found that there were issues with errors in the current release version of NixOS and with `luarocks` not being set in the path.
I will therefore fix these issues.
For verification purposes, we have also created a minimal `devshell` environment that runs the settings of this repository.
This will make it possible to verify using a `nix` environment, even if NixOS or HomeManager are not in place.
If there is a slight problem, you may need to put in the effort to keep `flake.lock` up to date.
This can be automated with github actions, just like updating `lazy-lock.json`.
Also, since it doesn't relate to the module part, you may want to update it only when necessary.

@CharlesChiuGit 
If possible, could you please confirm if this `devshell` works in an arm mac environment?
It will start with `nix develop`.

2024-04-30 02:11 UTC, CharlesChiuGit requested changes

2024-04-30 02:11 UTC, CharlesChiuGit commented on nixos/neovim/default.nix
>              luarocks
it's better to use `lua51Packages.luarocks` to align with the version of nvim-embeded lua

2024-04-30 02:11 UTC, CharlesChiuGit commented on nixos/neovim/default.nix
> +        withRuby = true;
i think it's better to set `withRuby` to false, since nvim's ruby plugin is not used in our config.

2024-04-30 02:12 UTC, CharlesChiuGit commented
> If possible, could you please confirm if this devshell works in an arm Mac environment?

ys, it does.
![image](https://github.com/ayamir/nvimdots/assets/32497323/77104d08-1238-4f20-82d7-43f63da13b8f)

2024-04-30 02:20 UTC, CharlesChiuGit commented
> This can be automated with github actions, just like updating `lazy-lock.json`.
Also, since it doesn't relate to the module part, you may want to update it only when necessary.
I would like to add github actions if necessary.

agree, it would be nice.

2024-04-30 02:46 UTC, misumisumi commented
I tried excluding unsupported packages, will this work?

2024-04-30 02:49 UTC, misumisumi commented
> This can be automated with github actions, just like updating lazy-lock.json.
Also, since it doesn't relate to the module part, you may want to update it only when necessary.
I would like to add github actions if necessary.

I had raised an ambiguous problem.,
Is this a positive statement, whether it is better to add a workflow or not?

2024-04-30 02:52 UTC, CharlesChiuGit commented
> Is this a positive statement, whether it is better to add a workflow or not?

ys, add a github action would be nice.

2024-04-30 03:14 UTC, CharlesChiuGit requested changes

2024-04-30 03:14 UTC, CharlesChiuGit commented on nixos/neovim/default.nix
> +        libgcc.lib
when i tried to do `nix develop --show-trace`, at the very end, it shows:
```
       … while selecting an attribute
         at /nix/store/mmcw46lk4pfgjz2pys7rhc6ra4mqxk88-source/nixos/neovim/default.nix:77:9:
           76|         glibc
           77|         libgcc.lib
             |         ^
           78|         libsodium

       error: expected a set but found null: null
```
and i couldn't find `libgcc.lib` and `stdenv.cc.cc` in nixpkg, but only `libgcc` and `stdenv`. Is this some nix syntax i don't know or we actually dont need the `.lib` and `.cc.cc` part.

2024-04-30 05:06 UTC, misumisumi commented on nixos/neovim/default.nix
> +        libgcc.lib
`.lib` and `.cc.cc` are necessary.
These are like `*-dev` on ubuntu.
I checked and found that libgcc does not exist on darwin.
This is due to the use of `clang` on darwin.
Therefore, I made it so that it references `stdenv.cc.cc.lib` instead of `libgcc.lib`.
`stdenv.cc.cc.lib` is a wrapper for `libgcc.lib` on linux and `clang.lib` on darwin.

2024-04-30 05:14 UTC, CharlesChiuGit commented on nixos/neovim/default.nix
> +        libgcc.lib
tks for explanation!

2024-04-30 05:26 UTC, CharlesChiuGit commented on nixos/neovim/default.nix
> +        libgcc.lib
it works now, nice!
![image](https://github.com/ayamir/nvimdots/assets/32497323/a1294125-e889-4722-becb-928b7383bbbe)

2024-04-30 05:29 UTC, CharlesChiuGit commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
`-r` flag doesn't exists on darwin too.
![image](https://github.com/ayamir/nvimdots/assets/32497323/f7ea8a17-2897-4f2e-a954-db52d2fa1a0c)

![image](https://github.com/ayamir/nvimdots/assets/32497323/36975381-66d0-4c6d-8d8a-a5311847cfc6)
is this flag necessary?

2024-04-30 05:31 UTC, misumisumi commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
Ah.
It was still the old setting.
I'll fix it.

2024-04-30 05:31 UTC, misumisumi commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
As mentioned earlier, nixpkgs' stdenv uses gcc on Linux and clang on Darwin, but what about `mason.nvim`?
Do I need to change any environment variables?

2024-04-30 05:53 UTC, misumisumi commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
Will this work?

2024-04-30 06:01 UTC, CharlesChiuGit commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
seems fine on my end.
![image](https://github.com/ayamir/nvimdots/assets/32497323/72ef0ccb-6326-496d-ac59-20943d7c5e97)

2024-04-30 06:03 UTC, misumisumi commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
Did you also build the package?

2024-04-30 06:11 UTC, CharlesChiuGit commented on flake.nix
> +                      ln -rsf "''${path}" "''${XDG_CONFIG_HOME}"/nvimdots/
ys, all LSP managed by mason works fine.
![image](https://github.com/ayamir/nvimdots/assets/32497323/c0dfab58-7828-46b4-9924-5c670554d7a5)

![image](https://github.com/ayamir/nvimdots/assets/32497323/46fbf3fd-3dd1-4ecb-9005-ef2fb887db9f)

2024-04-30 06:13 UTC, misumisumi commented
I try not to place lazy-lock.json under $XDG_CONFIG_HOME/nvimdots, but should I place it there?
I have been avoiding the lock file because it seems to be updated on the first startup.

2024-04-30 06:27 UTC, CharlesChiuGit commented
`copilot.lua` and `nvim-nio` keeps failing to checkout no matter what i do.
![image](https://github.com/ayamir/nvimdots/assets/32497323/b86563ba-6920-464e-84df-21f0c14a5254)
i tried remove those two plugins in `~/.local/share/nvimdots/site/lazy` and let `lazy` reinstall it, but it just keeps failing. I cant tell what could cause the issue.

2024-04-30 06:32 UTC, CharlesChiuGit commented
> I have been avoiding the lock file because it seems to be updated on the first startup.

interesing, this issue doesn't seem to happen on my end.

> I try not to place lazy-lock.json under $XDG_CONFIG_HOME/nvimdots, but should I place it there?

i'm fine placing the lock file in or out, as long as it got managed by the user or  via our nvim config. Personally i like to place the lock file in `$XDG_CONFIG_HOME/nvimdots`, so it's faster for me to debug if needed.

2024-04-30 11:53 UTC, Jint-lzxy commented
> i tried remove those two plugins in `~/.local/share/nvimdots/site/lazy` and let `lazy` reinstall it, but it just keeps failing. I cant tell what could cause the issue.

@CharlesChiuGit Would verbose logging provide additional insights?
```sh
cd ~/.local/share/nvimdots/site/lazy/copilot.lua/
git status && GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE_PACKET=1 GIT_TRACE_SETUP=1 GIT_TRACE_SHALLOW=1 git restore --source=HEAD :/
```
I once came across this and eventually realized it was a permission issue. Specifically, the default umask got accidentally changed, leaving that git folder wide open for everyone.
***
By the way can u please help me do a sanity check to ensure that the executables are correctly linked on macOS? I'm just diving into Nix so I might not be much help here. Basically, all u need to do is run `otool -L` on some of the MachO binaries produced by Nix or Mason and confirm whether they're indeed using packages (libraries) provided by Nix rather than those by the system (this ensures that `dyld` is doing the right thing and that packages can be located correctly with our config).

2024-04-30 13:39 UTC, misumisumi commented
> By the way can u please help me do a sanity check to ensure that the executables are correctly linked on macOS? I'm just diving into Nix so I might not be much help here. Basically, all u need to do is run otool -L on some of the MachO binaries produced by Nix or Mason and confirm whether they're indeed using packages (libraries) provided by Nix rather than those by the system (this ensures that dyld is doing the right thing and that packages can be located correctly with our config).

Maybe I can incorporate a simple test script into `flake.nix`.
However, I have never written a proper test script, so I need to check the home-manager test scripts, etc.
I'm busy tomorrow, so I'll work on it again after Thursday.

2024-05-02 05:55 UTC, CharlesChiuGit commented
> `copilot.lua` and `nvim-nio` keeps failing to checkout no matter what i do, but it works fine outside nix devshell.

omg, it suddenly works w/o any modification. it's so weird lol
![image](https://github.com/ayamir/nvimdots/assets/32497323/7123ec0b-e958-4c72-83c2-77058841581c)

2024-05-02 05:58 UTC, CharlesChiuGit commented
> can u please help me do a sanity check to ensure that the executables are correctly linked on macOS?

ok, let me check. hope i will know how to use those tools soon lol

2024-05-02 06:10 UTC, misumisumi commented
Fixed thiree things.
One is put `lazy-lock.json` under `$XDG_CONFIG_HOME/$NVIM_APPNAME`.
Two is rename `test.nix` to `testEnv.nix`.
Three is adding `check-linker` script.
This is simply script to check whether binary installed by mason link to `/nix/store`.
Print cmd name and target lib if not link.

2024-05-02 06:16 UTC, CharlesChiuGit commented
seems working exactly like we wanted!
![image](https://github.com/ayamir/nvimdots/assets/32497323/2fca60d1-6d36-40f9-a0b2-9b11e209764b)

2024-05-02 06:35 UTC, CharlesChiuGit commented
![image](https://github.com/ayamir/nvimdots/assets/32497323/d72b9474-eead-4097-adfb-212e045b27bb)

2024-05-02 06:39 UTC, misumisumi commented
I have probrem, loop never reaches the end in linux.
Please wait a moment while I fix it.

2024-05-02 07:05 UTC, misumisumi commented
It stopped because `set -o pipefail` was set when grep did not match.
Also, some packages could not find libraries because there was no `LIBRARY_PATH` and so on set in `nvim`.
Therefore, I have made it so that the environment variables set in `nvim` are `source`.

2024-05-02 07:26 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
minor typo:
`-n-1` -> `-n 1`
![image](https://github.com/ayamir/nvimdots/assets/32497323/b38a5aaa-4be4-4b6a-b974-c0694903d12b)

2024-05-02 07:28 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
Maybe Mac's head doesn't allow negative numbers?
When use negative numbers in GNU ver, output excluding the last n lines.

2024-05-02 07:29 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
aha, then `-n -1`

2024-05-02 07:34 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
![image](https://github.com/ayamir/nvimdots/assets/32497323/4422c5f1-e421-4400-bc63-351a48480ffb)
hmmm, it seems it cant take `-1`...

2024-05-02 07:45 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
`source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")`

why sourcing last line of this file?

2024-05-02 07:45 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
use `sed` instead of `head`.
Can you run cmd ?

2024-05-02 07:47 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
on `aarch64-darwin`:
![image](https://github.com/ayamir/nvimdots/assets/32497323/646f183e-b6a2-4baa-8e98-c51b93c6224c)

on `aarch64-linux`:
![image](https://github.com/ayamir/nvimdots/assets/32497323/ba01bb9e-4f52-4c41-a261-cf780410134d)

2024-05-02 07:50 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
Can you show me the output of `ldd $(readlink -f ~/.local/share/nvim/mason/bin/stylua)`?

2024-05-02 07:52 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
ohno, macos doesn't ship with `ldd`, so we need to add this in our pakcages. all results above might be invalid.
![image](https://github.com/ayamir/nvimdots/assets/32497323/186ed261-cce0-45ad-bf47-5ae125eff6da)

2024-05-02 07:55 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
using `otool -L` on `aarch64-darwin`:
![image](https://github.com/ayamir/nvimdots/assets/32497323/7378147d-10f7-4b8d-b856-ec6ca3389f0e)

2024-05-02 07:56 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
ldd uses ld to load executable files, and recursively loads dynamically-linked libraries. So using ldd requires being on the target system (e.g., Linux). Thus, ldd cannot be used for ELF files on macOS.

https://stackoverflow.com/a/67818942

2024-05-02 07:57 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
Ah. I change using `glibc` in nixpkgs.

2024-05-02 08:02 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
sadly
```
error: Package ‘glibc-nolibgcc-2.39-5’ in /nix/store/qxrwp9qzj2by5vqy4gm6f29njjkw4cna-source/pkgs/development/libraries/glibc/default.nix:184 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
```

2024-05-02 08:04 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
on `aarch64-linux`:
![image](https://github.com/ayamir/nvimdots/assets/32497323/f92fff8b-1558-4447-b71d-02e1cfd57e71)

2024-05-02 08:13 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
i think it easier for us to use `otool -L` on darwin and `ldd` on linux.

2024-05-02 08:30 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
Maybe, could have fixed it.

2024-05-02 08:37 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
> on aarch64-linux:

This may be a problem due to respecting the currently set LIBRARY_PATH and so on.
I think if you remove `nvimdots/mason`, make sure that no environment variables are set, and then install and build again, it will link to.

2024-05-02 08:47 UTC, CharlesChiuGit commented
seems like we need to use multiple version of `glibc` on aarch64-linux?
![image](https://github.com/ayamir/nvimdots/assets/32497323/fcf97c23-c46e-406d-b7bf-b97912710118)

2024-05-02 09:00 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
i removed `~/.local/share/nvim/mason`, reinstalled, but still the same.
![image](https://github.com/ayamir/nvimdots/assets/32497323/0eb15952-2a5a-494b-8217-c1a08eb25cae)

2024-05-02 09:04 UTC, misumisumi commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
Maybe `stylua` is provided as a binary package.
I think that `mason.nvim` is designed to use the binary if it is provided, and build it if it is not.

2024-05-02 09:16 UTC, CharlesChiuGit commented on flake.nix
> +                source <(head -n-1 "${self.packages.${system}.testEnv}/home-path/bin/nvim")
aha, ys. it should be the case.
https://github.com/mason-org/mason-registry/blob/main/packages/stylua/package.yaml

2024-05-02 09:19 UTC, misumisumi commented
Can you check node path with `readlink -f $(which node`?
Maybe use system wide node.

2024-05-02 09:39 UTC, CharlesChiuGit commented
![image](https://github.com/ayamir/nvimdots/assets/32497323/21be4629-3b30-449b-82de-2cd86493f58a)
 oh damn, it is using the system node.

2024-05-02 11:06 UTC, CharlesChiuGit commented
i disable system node temporarily and enter devshell, now all `node/npm` relate installation works porperly.

2024-05-02 11:30 UTC, misumisumi commented
Finally, regarding the github actions that update `flake.lock`, should I update `flake.lock` when updating `lazy-loc.json`, or should I update `flake.lock` separately?
Also, is it better to open a PR before updating, like with dependabot?

2024-05-03 01:52 UTC, CharlesChiuGit commented
I prefer update `flake.lock` separately, since I think update it once a month is enough.

And I prefer to update `flake.lock` directly w/o opening a PR.

2024-05-03 05:52 UTC, misumisumi commented
I add workflow of auto flake update.
This is called at 2:30 (UTC) of 1st of every month

2024-05-03 11:58 UTC, misumisumi commented
I think all the work is completed, what do you think?

2024-05-03 14:37 UTC, CharlesChiuGit commented
1. Set check linker uses `otool -L` on `aarch64-darwin` and `ldd` on `linux`.
2. Below error haven't been fixed:
```
error: Package ‘glibc-nolibgcc-2.39-5’ in /nix/store/qxrwp9qzj2by5vqy4gm6f29njjkw4cna-source/pkgs/development/libraries/glibc/default.nix:184 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
```

2024-05-03 14:53 UTC, CharlesChiuGit commented
i'll test it next week or maybe @Jint-lzxy can help lol

2024-05-06 02:18 UTC, CharlesChiuGit approved these changes
![image](https://github.com/ayamir/nvimdots/assets/32497323/ca5ba2b7-d681-498b-8b26-06a3f00356f1)
![image](https://github.com/ayamir/nvimdots/assets/32497323/6f6d5ecd-fb3e-4c7e-88d5-8d65c6d32654)
looks fine on both `aarch64-darwin` and `aarch64-linux`

2024-05-06 05:16 UTC, merged

2024-05-06 15:56 UTC, Jint-lzxy commented
> > can u please help me do a sanity check to ensure that the executables are correctly linked on macOS?
> 
> sure, let me check. hope i will know how to use those tools soon lol

@CharlesChiuGit Apple does indeed have a [thorough documentation](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html) on dynamic library usage tucked away in its documentation archives (way better than what it offers nowadays lol). It's definitely worth a look if u're into this stuff XD

2024-05-06 16:09 UTC, misumisumi commented
@CharlesChiuGit @CharlesChiuGit 
The wiki needs to be updated.
We'll be working on that soon.
We'll report back here when it's done.