Feat/telescope collections keymaps
ayamir/nvimdots pull request #1303
Opened 2024-06-20 01:45 UTC by ayamir

#1299

2024-06-20 02:06 UTC, CharlesChiuGit commented
what(
i dont get it?

2024-06-20 03:05 UTC, CharlesChiuGit approved these changes
LGTM

2024-06-20 05:25 UTC, Jint-lzxy reviewed
Shall we also update `dots.tutor` here as well? I think it would be great to introduce this to new users lol

2024-06-20 05:44 UTC, Jint-lzxy requested changes

2024-06-20 05:44 UTC, Jint-lzxy commented on lua/modules/configs/ui/alpha.lua
> +			icons.documents.FileFind .. "Telescope file",
```suggestion
			icons.documents.FileFind .. "Find files",
```

imo it's a bit weird to call that "Telescope file," especially for newcomers ~~(or maybe they just wanna find files in the Milky Way, who knows)~~. Perhaps "Find files" would be better?

2024-06-20 05:44 UTC, Jint-lzxy commented on lua/modules/configs/ui/alpha.lua
> +			icons.ui.FolderWithHeart .. "Telescope rootdir",
```suggestion
			icons.ui.FolderWithHeart .. "Retrieve dossiers",
```
Same here. Tho I can't seem to find a better word than `dossier`; any good ideas?

2024-06-20 05:44 UTC, Jint-lzxy commented on lua/modules/configs/ui/alpha.lua
> +			icons.documents.Word .. "Telescope word",
```suggestion
			icons.documents.Word .. "Find patterns",
```
ditto

2024-06-20 05:44 UTC, Jint-lzxy commented on lua/modules/configs/ui/alpha.lua
> +			icons.git.Git .. "Telescope git",
```suggestion
			icons.git.Git .. "Locate Git objects",
```
ditto

2024-06-20 05:44 UTC, Jint-lzxy commented on lua/modules/configs/ui/alpha.lua
> +			icons.misc.Ghost .. "Telescope misc",
```suggestion
			icons.misc.Ghost .. "Miscellaneous artifacts",
```
Errrr I'm running out of ideas here lol

2024-06-20 06:11 UTC, ayamir commented
The reason I changed the key bindings was to keep them as consistent with old keymaps as possible.

2024-06-20 06:12 UTC, ayamir commented
> Shall we also update `dots.tutor` here as well? I think it would be great to introduce this to new users lol

forgot this, will commit for it later.

2024-06-20 15:38 UTC, Jint-lzxy commented
@ayamir I've replaced all instances of "root directory management" with either "(current) working directory management" or "dossier management" bc I really couldn't find any references to the original term. Could u kindly explain why u chose that term, as I might have missed something (quite likely lol)?

2024-06-21 01:49 UTC, ayamir commented
> @ayamir I've replaced all instances of "root directory management" with either "(current) working directory management" or "dossier management" bc I really couldn't find any references to the original term. Could u kindly explain why u chose that term, as I might have missed something (quite likely lol)?

It's ok for me. The reason why I use `rootdir` is to keep consistency with the keymap i.e. `<leader>fr`. BTW, `<leader>fw` is better to keep the functionality to find "word" IMO. We should not be able to introduce or introduce new keymaps to prevent custom configuration conflicts with users.

2024-06-21 04:10 UTC, Jint-lzxy commented
> We should introduce no or as few new keymaps as possible to prevent conflicts with user customizations.

Yeah, that's true, but I don't think it's ideal for long-term use since the way Telescope works has _fundamentally_ changed. For example, `collection = "word"` isn't really searching for a specific "word" but rather "patterns" in a broader sense, and `collection = "rootdir"` isn't just about projects' root directories but encompasses general dossier management (or a _collection_ of files). For instance, `Zoxide` operates on the current directory, which isn't necessarily the _root_ directory unless we're specifically referring to [chroot(2)](https://man.freebsd.org/chroot(2)) or the current _project's_ root directory. afaiu \*BSD, macOS, and probably Linux (though I'm not as familiar) never use "root directory" in the context of [chdir(2)](https://man.freebsd.org/chdir(2)). So imho it's indeed challenging to rebuild that muscle memory, but creating a mnemonic is far more important for me lol

> The reason why I use `rootdir` is to keep consistency with the keymap i.e. `<leader>fr`.

... hence I would suggest changing `rootdir` to `dossier`, and the corresponding keymap to `<leader>fd`

> BTW, `<leader>fw` is better to keep the functionality to find "word" IMO.

... and use `<leader>fp` for `pattern`.

2024-06-21 06:21 UTC, ayamir commented
OK, it's fine to me.

2024-06-21 09:20 UTC, merged