feat(script): Complete installation script on Windows.
ayamir/nvimdots pull request #452
Opened 2023-01-29 17:17 UTC by Jint-lzxy

Resolves #448. @ayamir Can you test this script on Windows? It executes correctly on macOS running `pwsh core`.

Command:
```pwsh
Invoke-WebRequest "https://raw.githubusercontent.com/Jint-lzxy/nvimdots/feat/windows-installer/install/install.ps1" -UseBasicParsing | Invoke-Expression
```

2023-01-29 17:18 UTC, Jint-lzxy commented
It installs the configuration to `$env:LOCALAPPDATA\nvim` by default.

2023-01-29 17:49 UTC, CharlesChiuGit commented
I just ran the command directly. Do I need to set sth else?

![圖片](https://user-images.githubusercontent.com/32497323/215345600-7a3b892c-c8ac-4d1e-abdc-78a6fab15ce7.png)

2023-01-30 02:25 UTC, ayamir commented
Execute this command directly failed. 

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/61657399/215374578-316f3530-38bf-4087-9ee5-e47a5eb29eda.png">


But it succeeded after I download this script manually and execute it.

2023-01-30 04:39 UTC, CharlesChiuGit commented
I ran the script on a fresh win11 machine with following steps:

1. ```Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass``` to make the ps1 file can be runable.
2. Install scoop and `scoop install neovim`.
3. Grep the script and run it.
4. Most of the plugin cloned successfully, but the plugins require other tools like `nodejs`, `cargo`, `make`, `cmake`, `python` etc will fail as expected.

![圖片](https://user-images.githubusercontent.com/32497323/215384497-203b0d31-6630-46e1-811d-63f50ec8ef44.png)

```log
[ERROR 2023/1/30 ¤W¤È 04:01:01] ...a\site\lazy\mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=black) error="...te\\lazy\\mason.nvim/lua/mason-core/managers/pip3/init.lua:90: Unable to create python3 venv environment."
[ERROR 2023/1/30 ¤W¤È 04:01:01] ...a\site\lazy\mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=prettier) error=spawn: npm.cmd failed with exit code - and signal -. npm.cmd is not executable
```

Things that failed to install or having errors:
1. tree-sitter parsers
2. Luasnip(fix: install `make`)
3. telescoop-fzf-native.nvim(fix: `scop install fzf)
4. markdown-preview.nvim(fix: install `nodejs`)
5. sniprun(fix: install `cargo`)
6. prettier(fix: install `nodejs`)
7. black(fix: install `python`?)
8. pyright
9. bashls
10. gopls
11. efm

I think the script is good to go.

Just the command you mentioned is still not able to run directly with following error. (Powershell 7.3.2)
![圖片](https://user-images.githubusercontent.com/32497323/215385235-1cc8b7a3-13e4-4621-aa93-cd2ff2fe2191.png)

2023-01-30 05:11 UTC, Jint-lzxy commented
Thanks for the information 👍 I will try to use `Winget`/`Chocolatey`/`Scoop` to fetch necessary packages _(Users may choose from them)_.

2023-01-30 05:13 UTC, Jint-lzxy commented
> Execute this command directly failed.
> 
> <img alt="image" width="1086" src="https://user-images.githubusercontent.com/61657399/215374578-316f3530-38bf-4087-9ee5-e47a5eb29eda.png">
> 
> But it succeeded after I download this script manually and execute it.

All necessary environment variables will be set before this in the next push 👍

2023-01-30 05:16 UTC, Jint-lzxy commented
So now we need to:
1. Properly setup `pwsh` to accept scripts from any source;
2. Set up the environment correctly _(this script cannot run in a completely clean environment as `Set-StrictMode -Version 3.0`)_
3. Complete the installation of dependencies in the install script

2023-01-30 05:20 UTC, Jint-lzxy commented
> > I just ran the command directly. Do I need to set sth else? btw, I'm using `powersehll`, not `windows powershell`. Does that make a difference?
> > ![圖片](https://user-images.githubusercontent.com/32497323/215345600-7a3b892c-c8ac-4d1e-abdc-78a6fab15ce7.png)
> 
> It just require `powershell` version `7.1`, it's `powershell` instead of `windows powershell`.

Emm This script would only need `pwsh core` to execute successfully. It doesn't matter what pre-/suffixes `pwsh` have... I will fix these errors on my Windows 10 VM later.

2023-01-30 05:27 UTC, Jint-lzxy commented
> I just ran the command directly. Do I need to set sth else? btw, I'm using `powersehll`, not `windows powershell`. Does that make a difference?
> 
> ![圖片](https://user-images.githubusercontent.com/32497323/215345600-7a3b892c-c8ac-4d1e-abdc-78a6fab15ce7.png)

Maybe this issue is related to the prefix `???`? I will use raw strings or just download it to the `TMP` folder and then run the script there.

2023-01-30 05:35 UTC, Jint-lzxy commented
`(System.Net.WebClient).DownloadString` will be used instead, this works fine

2023-01-30 05:46 UTC, CharlesChiuGit commented
> Thanks for the information 👍 I will try to use `Winget`/`Chocolatey`/`Scoop` to fetch necessary packages _(Users may choose from them)_.

`winget` would be nice! Since it's built-in, but I'm not sure if winget can handle github source that well, like `fzf` or most of the lsps.

2023-01-30 05:54 UTC, Jint-lzxy commented
> > Thanks for the information 👍 I will try to use `Winget`/`Chocolatey`/`Scoop` to fetch necessary packages _(Users may choose from them)_.
> 
> `winget` would be nice! Since it's built-in, but I'm not sure if winget can handle github-sourced tools that well, like `fzf` or most of the lsps.

Hmm then IMO we should just use `Chocolatey` or `Scoop`. Although we have `Mason` in nvim, some of its dependencies still can't be installed by `winget` :(

I think we can support `winget` after it supports all packages we need.

2023-01-30 05:58 UTC, CharlesChiuGit commented
Yeah, totally agreed. Personally I like `scoop` better since it doesn't need admin privileges, which would be vital for ppl who wants to install this config on their work machine.

2023-01-30 06:03 UTC, Jint-lzxy commented
@CharlesChiuGit I have a small question. Now the script will try to use a command and its `.exe` suffix form _(e.g., `git` and `git.exe`)_ to avoid the case when users didn't add the symlink of non-suffixal form _(e.g., `git`)_ to his `PATH`.
```pwsh
if ($hasEXEnvim) {
  $nvim_version = Invoke-Command -ErrorAction SilentlyContinue -ScriptBlock { **nvim.exe** --version }
} else {
  $nvim_version = Invoke-Command -ErrorAction SilentlyContinue -ScriptBlock { **nvim** --version }
}
```
Are those checks necessary? I'm not a Windows user, so don't know much about this :(

2023-01-30 06:25 UTC, Jint-lzxy commented
I decided to remove these checks. It should be the user's responsibility to ensure that the command exists.

2023-01-30 07:03 UTC, CharlesChiuGit commented
I think it's not necessary, since we're running the command in a script. For example I installed `git.exe`, but I can call `git` in `pwsh` as in linux/macOS.(Sorry I got caught up by my boss.

![圖片](https://user-images.githubusercontent.com/32497323/215409342-bd9b2508-6e76-4911-84d6-676040ca2c53.png)

2023-01-30 07:17 UTC, Jint-lzxy commented
> > I just ran the command directly. Do I need to set sth else? btw, I'm using `powersehll`, not `windows powershell`. Does that make a difference?
> > ![圖片](https://user-images.githubusercontent.com/32497323/215345600-7a3b892c-c8ac-4d1e-abdc-78a6fab15ce7.png)
> 
> Maybe this issue is related to the prefix `???`? I will use raw strings or just download it to the `TMP` folder and then run the script there.

Update: Located this issue:
```console
❯ xxd install/install.ps1
00000000: efbb bf23 5265 7175 6972 6573 202d 5665  ...#Requires -Ve
```
🤦‍♂️🤦‍♂️There is an issue with the formatter as it runs on Windows by default, should tell we're running on macOS :(

2023-01-30 10:21 UTC, Jint-lzxy commented
https://github.com/ayamir/nvimdots/pull/452/commits/7a58e6fd6500c88322ee0d5a93ab7e1c1e3a14af implemented package manager support.

The correct command is:
```pwsh
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Jint-lzxy/nvimdots/feat/windows-installer/install/install.ps1'))
```

2023-01-30 10:24 UTC, Jint-lzxy commented
@CharlesChiuGit @ayamir Now all the above issues have been resolved 👍

When testing, it is best to uninstall (some of) the following dependencies to test whether `Check-And-Fetch-Exe` works properly
```pwsh
$choco_package_matrix = @{ "git" = "git"; "nvim" = "neovim"; "make" = "make"; "node" = "nodejs"; "pip" = "python3"; "fzf" = "fzf"; "go" = "go"; "curl" = "curl"; "wget" = "wget"; "tree-sitter" = "tree-sitter"; "ruby" = "ruby"; "rustc" = "rust-ms" }
```

2023-01-30 10:25 UTC, CharlesChiuGit commented
Will test after I got home!

2023-01-30 13:28 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215488452-357e5fae-51cc-4efc-8694-668e7957be67.png)
![圖片](https://user-images.githubusercontent.com/32497323/215490168-f1503d7d-c9eb-4511-9c3d-efbf6ff9b91f.png)

I stuck at the second picture, running with scoop.

2023-01-30 13:36 UTC, Jint-lzxy commented
Fixed at https://github.com/ayamir/nvimdots/pull/452/commits/c35905236045a17bc78c13db0464b9f2a58f434d. Also run `npm install -g npm@9.4.0` first 👍

2023-01-30 13:42 UTC, Jint-lzxy commented
Wait a minute. The real issue should be `pip` is not initialized.

2023-01-30 13:43 UTC, CharlesChiuGit commented
I found one interesting issue. It seems like the newly installed app aren't being registered in PATH unless one do a logout/login or a restart. `node` and `ruby` didn't being pick up after fresh install, even open a new shell.

2023-01-30 13:44 UTC, Jint-lzxy commented
> I found one interesting issue. It seems like the newly installed app aren't being registered in PATH unless one do a logout/login or a restart. `node` and `ruby` didn't being pick up after fresh install, even open a new shell.

@CharlesChiuGit Yeah I also realized that. Will do:
```pwsh
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
```

2023-01-30 13:47 UTC, Jint-lzxy commented
Fixed at https://github.com/ayamir/nvimdots/pull/452/commits/5974f70f029d80a86a4bfb2a6096aae4ea90103c

2023-01-30 13:59 UTC, Jint-lzxy commented
> I found there's a `dark` package being installed before installing `python`, is that intended?

Yeah I believe that's intended 😄AFAIK `dark` is the WiX (Windows Installer XML) Toolset Decompiler, to install `python` we would need that decompiler

2023-01-30 14:38 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215498011-61ae2fcf-9316-4e68-91e9-f22eb3a1ea6d.png)

I'm not sure if MSYS2 is needed, but it seems nice to include a line of `ridk install`?

![圖片](https://user-images.githubusercontent.com/32497323/215506258-f854a642-8652-4c9f-8aa1-580ba19987d2.png)

I think we should consider including `wheel` and `pyproject.toml` before installing `pynvim`, for it might be deprecated soon.

![圖片](https://user-images.githubusercontent.com/32497323/215506585-fc06c30e-eec9-4dcb-976b-c3e09f65ba02.png)

And finally, I still got that weird error below after all plugins and ts parsers are install successfully by lazy.

```ps1
cmdlet prompt at command pipeline position 1
Supply values for the following parameters:
Msg:
```

2023-01-30 14:42 UTC, CharlesChiuGit commented
One small thing:
I think we should consider replacing this line
https://github.com/ayamir/nvimdots/blob/c313d5262a9b224e2958b1c31bd7097473c69861/lua/modules/lang/plugins.lua#L19

with 
```lua
	build = function()
		vim.fn["mkdp#util#install"]()
	end,
```
The later seems work faster than the previous one.

2023-01-30 14:48 UTC, Jint-lzxy commented
Fixed at: https://github.com/ayamir/nvimdots/pull/452/commits/a8bf97bf7f73032c0aa6fd27a722c8b57327ceda

2023-01-30 14:57 UTC, Jint-lzxy commented
> One small thing: I think we should consider replacing this line
> 
> https://github.com/ayamir/nvimdots/blob/c313d5262a9b224e2958b1c31bd7097473c69861/lua/modules/lang/plugins.lua#L19
> 
> with
> 
> ```lua
> 	build = function()
> 		vim.fn["mkdp#util#install"]()
> 	end,
> ```
> 
> The later seems work faster than the previous one. (I use the later in my personal config and it worked fine.

Good catch! Just a quick note, the vim function can be directly called via:
```lua
lang["iamcco/markdown-preview.nvim"] = {
	lazy = true,
	ft = "markdown",
	-> build = ":call mkdp#util#install()",
}
```

2023-01-30 14:57 UTC, CharlesChiuGit commented
Interesting! Will steal. lol

2023-01-30 15:14 UTC, CharlesChiuGit requested changes
Minor thingy

2023-01-30 15:14 UTC, CharlesChiuGit commented on install/install.ps1
> +		Safe-Execute -WithCmd { git clone -b 0.7 'git@github.com:ayamir/nvimdots.git' "$env:CCDEST_DIR" }
I think we should use `git clone --depth=1` to avoid cloning extra things to the user.

2023-01-30 15:14 UTC, CharlesChiuGit commented on install/install.ps1
> +		Safe-Execute -WithCmd { git clone -b "$env:CCLONE_BRANCH" 'https://github.com/ayamir/nvimdots.git' "$env:CCDEST_DIR" }
Also this line too.

2023-01-30 15:14 UTC, CharlesChiuGit commented on install/install.ps1
> +		Safe-Execute -WithCmd { git clone -b 0.7 'https://github.com/ayamir/nvimdots.git' "$env:CCDEST_DIR" }
And this line lol

2023-01-30 15:15 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215516704-ae0b2a03-bb8c-4349-9b05-18b8e6be8940.png)

Still the same QQ

2023-01-30 17:29 UTC, CharlesChiuGit commented
> ![圖片](https://user-images.githubusercontent.com/32497323/215516704-ae0b2a03-bb8c-4349-9b05-18b8e6be8940.png)
> 
> Still the same QQ

I found this error occurs only when using 
```ps1
Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Jint-lzxy/nvimdots/feat/windows-installer/install/install.ps1'))
```

If I download the script and run it, the script will end successfully.

2023-01-30 19:23 UTC, CharlesChiuGit commented
I tried to find if there's any missing `-Msg` in the script, but it seems every `_abort`, `prompt`, `warn`, `warn-Ext` all have `-Msg`.

However, I also tried 
```ps1
irm https://raw.githubusercontent.com/Jint-lzxy/nvimdots/feat/windows-installer/install/install.ps1 | iex
```

still having 
```
cmdlet prompt at command pipeline position 1
Supply values for the following parameters:
Msg:
```

So I think it's more likely that sth is wrong in the script.

2023-01-31 01:15 UTC, Jint-lzxy commented
> cmdlet prompt at command pipeline position 1
> Supply values for the following parameters:
> Msg:

Will do a debug traceback now 👍

2023-01-31 02:18 UTC, Jint-lzxy commented
https://github.com/ayamir/nvimdots/pull/452/commits/98e32aea44d86e3e6f5e7049a10082652fb671f3 added an option for both scripts to check whether the user prefers shallow clone or a complete clone.

2023-01-31 02:29 UTC, Jint-lzxy commented
All problems have been resolved. Only one last full test is required before merging 👍

2023-01-31 02:55 UTC, CharlesChiuGit commented
Checking now( a lot of pending downloads lol

2023-01-31 03:00 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215651824-91fa3376-fe1c-40d0-b0b2-a7e597cbb7de.png)

New shallow clone function seems having a small issue.

2023-01-31 03:07 UTC, Jint-lzxy commented
Fixed at https://github.com/ayamir/nvimdots/pull/452/commits/7c575e0e3b619deb54e2c20ce97812eb0ba711a4

2023-01-31 03:12 UTC, CharlesChiuGit commented
Why does node pkg always took FOREVER to install... just saying...

2023-01-31 03:19 UTC, Jint-lzxy commented
> Why does node pkgs always took FOREVER to install... just saying...

There could be many causes for this... The versions of `npm` and `node` do not match those described in the spec; The user is behind a proxy...

Just answer `no` to NodeJS dependency installation 🥲

2023-01-31 03:23 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215654977-0915e4a5-1363-4d91-94df-135798fda42d.png)

I think we need to install `gcc` for this.

2023-01-31 03:31 UTC, Jint-lzxy commented
> I think we need to install `gcc` for this and ts parsers. (`scoop install gcc`)

I would choose `LLVM` as it's available on both package managers. (Sadly `msvc` and `gcc` are both only available on one of them ;(

The `LLVM` tool chain also provides some executables required for this configuration 👍

2023-01-31 03:32 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215655960-582ff788-0ff9-4f3d-b56a-ab3acec54cc5.png)

https://tenor.com/vfGo.gif

2023-01-31 03:34 UTC, Jint-lzxy commented
🤦‍♂️ @CharlesChiuGit What do you see if u supply that value (;

2023-01-31 03:39 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215656918-f64e2a52-9e0a-43f4-9e76-8f3934ad05c6.png)

Then I normally type `exit` in **PS>** and it close the shell.

2023-01-31 03:41 UTC, Jint-lzxy commented
🤦‍♂️ OK I'll just remove that `Mandatory = $True` restriction

2023-01-31 03:43 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215657556-56b4a670-3c69-4059-ac2c-f6c2c4b3cef0.png)

`llvm` seems to work only partially.

2023-01-31 03:48 UTC, Jint-lzxy commented
Then we would still need `msvc` installed.

I would remove `llvm` and let the user install [visual studio](https://visualstudio.microsoft.com/zh-hans/#vs-section) himself.

2023-01-31 03:51 UTC, CharlesChiuGit commented
bloody hell msvc 👎

2023-01-31 03:53 UTC, Jint-lzxy commented
Make sure to tick `Desktop development with C++` at the very least

2023-01-31 04:06 UTC, Jint-lzxy commented
https://github.com/ayamir/nvimdots/pull/452/commits/92c62a0cc2fe1e3bd9a10507d54aabd8fe154856 removed those restrictions 😅 Should work now

2023-01-31 04:23 UTC, CharlesChiuGit commented
The result is not ideal but acceptable.

My original pwsh promt:
![圖片](https://user-images.githubusercontent.com/32497323/215662613-3b525aaf-71ce-4c6e-a897-4cc9b8355ee9.png)

pwsh promt after installation:
![圖片](https://user-images.githubusercontent.com/32497323/215662898-a3063142-6324-4a97-b518-7e33a35ae51e.png)

I come up with another workaround. Maybe we can open a new terminal window and force quit that window so no one would saw that issue. How do u think?

2023-01-31 04:26 UTC, Jint-lzxy commented
(I just checked [mingw](https://scoop.sh/#/apps?q=mingw&s=0&d=1&o=true), it works fine) I personally don't want users to install other editors when installing this **neovim** config 😅

2023-01-31 04:27 UTC, CharlesChiuGit commented
> (I just checked [mingw](https://scoop.sh/#/apps?q=mingw&s=0&d=1&o=true), it works fine) I personally don't want users to install other editors when installing this **neovim** config 😅

Lamo 💯 💯 💯 1000% agreed.

2023-01-31 04:30 UTC, Jint-lzxy commented
> The result is not ideal but acceptable.
> 
> My original pwsh promt: ![圖片](https://user-images.githubusercontent.com/32497323/215662613-3b525aaf-71ce-4c6e-a897-4cc9b8355ee9.png)
> 
> pwsh promt after installation: ![圖片](https://user-images.githubusercontent.com/32497323/215662898-a3063142-6324-4a97-b518-7e33a35ae51e.png)
> 
> I come up with another workaround. Maybe we can open a new terminal window and force quit that window so no one would saw that issue. How do u think? ( I don't there's anyone run Windows headlessly.)
> 
> Aside from that, I think everything is good to go.(I use scoop's gcc for C compiling tho)

Oh God I forgot to exit from the install script :( That's the cause of all the issues
A "bash-sequela" 👎

2023-01-31 04:33 UTC, CharlesChiuGit commented
No... I think it that pwsh is just so fking weird. TBO, I'm respect u a lot, since I personally would not want to learn pwsh lol

2023-01-31 04:44 UTC, Jint-lzxy commented
Finally https://github.com/ayamir/nvimdots/pull/452/commits/d82f71d619b6f855d4622792780607a0c5658b3f

2023-01-31 04:51 UTC, Jint-lzxy commented
@CharlesChiuGit Hope this is the last test **ever** :(

Yeah `pwsh`'s syntax and **behavior** is just so weird.

2023-01-31 05:08 UTC, CharlesChiuGit commented
Nice! Everything works fine!

2023-01-31 05:09 UTC, CharlesChiuGit approved these changes
LGTM

2023-01-31 05:09 UTC, merged

2023-01-31 05:13 UTC, CharlesChiuGit commented
Final command:
```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force; irm https://raw.githubusercontent.com/ayamir/nvimdots/main/install/install.ps1 | iex

2023-01-31 05:22 UTC, Jint-lzxy commented
I would prefer full command name and `HEAD` as git ref:
```pwsh
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-WebRequest 'https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/install/install.ps1' | Invoke-Expression
```

2023-01-31 07:45 UTC, CharlesChiuGit commented
![圖片](https://user-images.githubusercontent.com/32497323/215697593-d0d28ad5-4960-44f4-958a-09b1b893d09f.png)

This guy asked too early lol