refactor(keymap): refactor plugin keymaps according to scopes
ayamir/nvimdots pull request #495
Opened 2023-02-09 08:11 UTC by CharlesChiuGit

2023-02-09 14:11 UTC, aarnphm commented
food for thought: I'm thinking about moving per plugin mapping to its corresponding config. So that the default keymap should only concern all of the basic movement and functionality from nvim that is independent of the plugin system.

2023-02-09 14:27 UTC, CharlesChiuGit commented
> food for thought: I'm thinking about moving per plugin mapping to its corresponding config init. So that the default keymap should only concern all of the basic movement and functionality from nvim that is independent of the plugin system.
> 
> ```lua
> editor["plugin"] = {
>   lazy = true
>   init = function()
>      local k = require "keymap.bind"
>      k.nvim_load_mapping {
>      ["..."] = ...
>      }
>   end
> }
> ```
> 
> It probably provide a better separation of concern.

I personally love this idea! I once done this with my own config. 
Two major issue might need to be addressed:
1. It will be a bit hard to debug. Since we might not use this config as our live nvim config, so we can't call `<C-p>` to see all existing keymaps.
2. This would make `plugins\{scope}.lua` super long, we should probably avoid that. We might need a `lua/modules/keymaps/{scopes}/{plugin-name}.lua` to avoid this.

Maybe we can come out with a better idea to solve above issues.

2023-02-09 14:35 UTC, aarnphm commented
> It will be a bit hard to debug or find duplicated keymaps. Since we might not use this config as our live nvim config, so we can't call <C-p> to see all existing keymaps.

Which-keys should solve this for us during `checkhealth` right?

> This would make plugins\{scope}.lua super long, we should probably avoid that. We might need a lua/modules/keymaps/{scopes}/{plugin-name}.lua to avoid this.
Agree with this point.

I don't like what I'm about to say, but `lua/modules/config/{scope}/{plugin}.lua` should takes a table, and then when users specify under `lua/modules/plugins/{scope}/{plugin}.lua` we can have something such as:

```lua
editor['plugin'] = require("modules.utils").create_config({lazy = true, ...}, require("editor.plugin"))
```

the default behaviour is all field under `require('editor.plugin')` will overwrite existing mapping provided to `create_config`

2023-02-09 14:38 UTC, aarnphm commented
I just realize that `create_config` is just vim.tbl_extend :)

2023-02-09 14:40 UTC, Jint-lzxy commented
@aarnphm I've once considered this idea, but IMO it would be better for users to query all keymaps in one place _(especially for those who are not familiar with the project structure - they may define keymaps in the wrong place if we put those keymaps into different files)_, and reduce merge conflicts as much as possible _(the options for each spec should be left to users, and as much as possible)_

It is indeed a good idea, but we should consider novices who are new to `neovim`. The ability to run out-of-box and easy to make modifications is also consequential.

Just some thoughts.

2023-02-09 14:40 UTC, CharlesChiuGit commented
> Which-keys should solve this for us during `checkhealth` right?

I'm not sure about that, I never got `which-key`'s `checkhealth` worked as expected.

2023-02-09 14:42 UTC, aarnphm commented
@Jint-lzxy makes sense. I think that the current refactor should achieve this as well.

2023-02-09 14:55 UTC, Jint-lzxy commented
> I don't like what I'm about to say, but `lua/modules/config/{scope}/{plugin}.lua` should takes a table, and then when users specify under `lua/modules/plugins/{scope}/{plugin}.lua` we can have something such as:
> 
> ```lua
> editor['plugin'] = require("modules.utils").create_config({lazy = true, ...}, require("editor.plugin"))
> ```
> 
> the default behaviour is all field under `require('editor.plugin')` will overwrite existing mapping provided to `create_config`
> 
> ```lua
> M.create_config = function(opts, override)
> ```
> 
> My only concern with `lua/modules/keymaps/{scopes}/{plugin-name}.lua` is that when you do file grep it will have like 3-4 files with the same name 😆

@aarnphm `lazy.nvim` provides [this feature](https://github.com/folke/lazy.nvim#-structuring-your-plugins), but FWIW it would be more difficult for new users to get started. See: [Wiki: Usage#add-a-new-plugin](https://github.com/ayamir/nvimdots/wiki/Usage#add-a-new-plugin). Telling users to add specs in one place and their own configuration in another place is much simpler IMO. Otherwise, we also need to explain how spec merging works, and it is likely that users will make mistakes when working with nested tables - TBH this could lead to countless issues 🤦‍♂️

2023-02-09 14:57 UTC, CharlesChiuGit commented
> TBH this could lead to countless issues 🤦‍♂️

Lmao, this one does put a smile on my face.

2023-02-09 15:03 UTC, Jint-lzxy commented
> @Jint-lzxy makes sense. I think that the current refactor should achieve this as well.

@aarnphm Feel free to open an issue to discuss a _more_ appropriate "compromise" 😄 It's hard to "meet some sort of balance" 🤣

2023-02-09 15:06 UTC, CharlesChiuGit commented
https://github.com/ayamir/nvimdots/discussions is another gd place to start this kind of discussions. TBH, it's a bit under used.

2023-02-09 15:10 UTC, CharlesChiuGit commented
Just found a stupid mistake. https://github.com/ayamir/nvimdots/commit/4d38042b9993b7792c02801223a84dc067740533 should be  
> rename: rename `pbind` to `bind` since it's not only for plugins

2023-02-09 15:15 UTC, Jint-lzxy commented
Fixed :)

2023-02-09 15:18 UTC, CharlesChiuGit commented
@Jint-lzxy omg, I don't ppl can do that! Any resources to learn this kind of magic?

2023-02-09 15:19 UTC, aarnphm commented
> @aarnphm Feel free to open an issue to discuss a _more_ appropriate "compromise" 😄 It's hard to "meet some sort of balance" 🤣

that's the million dollar question in software ain't it 😄

2023-02-09 15:21 UTC, Jint-lzxy commented
@CharlesChiuGit It's all about interactive rebasing and force-push :) See:

https://stackoverflow.com/questions/5509543/how-do-i-properly-force-a-git-push
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2023-02-09 15:22 UTC, CharlesChiuGit commented
@aarnphm Actually I very curious about how u structure your nvimdots. Mind sharing the link?

2023-02-09 15:22 UTC, CharlesChiuGit commented
> @CharlesChiuGit It's all about interactive rebasing and force-push :) See:
> 
> [stackoverflow.com/questions/5509543/how-do-i-properly-force-a-git-push](https://stackoverflow.com/questions/5509543/how-do-i-properly-force-a-git-push) [git-scm.com/book/en/v2/Git-Tools-Rewriting-History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

Appreciate that!

2023-02-09 15:24 UTC, aarnphm commented
> @aarnphm Actually I very curious about how u structure your nvimdots. Mind sharing the link?

https://github.com/aarnphm/editor my own fork of nvimdots 😄

2023-02-10 01:37 UTC, CharlesChiuGit commented
@Jint-lzxy Do u know what's 
```lua
	["o|m"] = map_callback(function()
		require("tsht").nodes()
	end):with_silent(),
```
It doesn't seem belong to any of current plugin, is this some legacy code?

2023-02-10 01:40 UTC, ayamir commented
> 

No, https://github.com/mfussenegger/nvim-treehopper

2023-02-10 01:44 UTC, CharlesChiuGit commented
> No, [mfussenegger/nvim-treehopper](https://github.com/mfussenegger/nvim-treehopper)

But this plugin is not listed in `plugins/editor.lua`. Do we need to add it back?

2023-02-10 04:12 UTC, CharlesChiuGit commented
@Jint-lzxy @aarnphm PTAL.
ayamir, I think it would be better not to bother u too much considering your current condition.

2023-02-10 04:36 UTC, Jint-lzxy commented
@CharlesChiuGit im a bit tied up at the moment, will push some changes later 👍

2023-02-10 09:01 UTC, aarnphm reviewed
quick comment from me. Probably still need another look from Jint

2023-02-10 09:01 UTC, aarnphm commented on lua/modules/plugins/tool.lua
> +	event = "UIEnter",
```suggestion
	event = "LazyVimStarted",
```

I think Telescope can be loaded after UIEnter.

2023-02-10 09:02 UTC, aarnphm commented on lua/modules/plugins/tool.lua
> +	event = "UIEnter",
oh nvm discard this comment

2023-02-10 09:03 UTC, CharlesChiuGit commented on lua/keymap/tool.lua
> +			_Command_panel()
ys it does

2023-02-10 09:03 UTC, CharlesChiuGit commented on lua/modules/configs/tool/toggleterm.lua
> +		if vim.fn.executable("lazygit") then
aha, forgot to change that lol

2023-02-10 09:04 UTC, aarnphm commented on lua/modules/plugins/tool.lua
> +	event = "UIEnter",
I don't think it should be `UIEnter` here. It will slow down StartupTime.

Telescope should be invoked when `Telescope` cmd is used.

2023-02-10 09:10 UTC, aarnphm commented on lua/modules/configs/tool/toggleterm.lua
> +	function _Lazygit_toggle()
Another note is that this remove cache object. So if user accidentally close the terminal (not exit), then the terminal won't be clean correctly.

Everytime this function is called, it will draw a new terminal windows instead.

2023-02-10 09:12 UTC, aarnphm commented on lua/modules/configs/tool/toggleterm.lua
> +	function _Lazygit_toggle()
Maybe a solution for this is to have a map for cache of all available cmd that can be toggled by ToggleTerm as a first step.

```lua
local cache = {lazygit=nil, htop=nil, python=nil}

...

if vim.fn.executable("lazygit") then
   if not cache.lazygit then 
      cache.lazygit = ...
   end
   cache.lazygit:toggle()
else
   ...
end
```

2023-02-10 09:17 UTC, CharlesChiuGit commented on lua/modules/configs/tool/toggleterm.lua
> +	function _Lazygit_toggle()
That's gd idea! Will do.

2023-02-10 09:22 UTC, ayamir commented
@aarnphm A collaborators invitation has sended for you, thanks for your contributions.

2023-02-10 09:30 UTC, CharlesChiuGit commented
I'm not sure if https://github.com/ayamir/nvimdots/commit/37f4f5e247c83f75c65f0cbeeaf0f98d9ad8f133 did cache toggleterm windoes or not. Not sure how to reproduce "accidentally close the terminal".

2023-02-10 09:32 UTC, aarnphm commented
I run into this issue when I forgot to close the terminal correct, so when trying to do `:q`, there is an error about a buffer still opening. 

It turns out to be the unclosed toggleterm buffer.

2023-02-10 09:39 UTC, aarnphm commented on lua/modules/configs/tool/toggleterm.lua
> +				lazygit:toggle()
```suggestion
				toggleterm_cache.lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float" })
				toggleterm_cache.lazygit:toggle()
```

2023-02-10 09:39 UTC, CharlesChiuGit commented
> I run into this issue when I forgot to close the terminal correct, so when trying to do `:q`, there is an error about a buffer still opening.
> 
> It turns out to be the unclosed toggleterm buffer.

Actually, non of above new toggleterm windows(lazygit, htop, python) can use `:q` to create a accidentally closed terminal.

2023-02-10 09:39 UTC, aarnphm commented on lua/modules/configs/tool/toggleterm.lua
> +				htop:toggle()
```suggestion
				toggleterm_cache.htop = Terminal:new({ cmd = "htop", hidden = true, direction = "float" })
				toggleterm_cache.htop:toggle()
```

2023-02-10 09:39 UTC, aarnphm commented on lua/modules/configs/tool/toggleterm.lua
> +				python:toggle()
```suggestion
				toggleterm_cache.python = Terminal:new({ cmd = "python3", hidden = true, direction = "float" })
				toggleterm_cache.python:toggle()
			elseif vim.fn.executable("python") then
				toggleterm_cache.python = Terminal:new({ cmd = "python", hidden = true, direction = "float" })
				toggleterm_cache.python:toggle()
```

2023-02-10 09:40 UTC, aarnphm commented on lua/modules/configs/tool/toggleterm.lua
> +				python:toggle()
^^ This is how you cache it 😄

2023-02-10 09:52 UTC, aarnphm commented
> > I run into this issue when I forgot to close the terminal correct, so when trying to do `:q`, there is an error about a buffer still opening.
> > It turns out to be the unclosed toggleterm buffer.
> 
> Actually, non of above new toggleterm windows(lazygit, htop, python) can use `:q` to create an accidentally closed terminal.

Oh, because I have implement an on_open hook that bind q to close the current buffer.

2023-02-10 10:06 UTC, aarnphm approved these changes
LGTM

2023-02-10 10:08 UTC, CharlesChiuGit commented
@aarnphm Do u might port this cache mechanism to your own config? I still can't reproduce accidentally quit terminal after adding `q` to quit terminal.

2023-02-10 10:12 UTC, aarnphm commented
> @aarnphm Do u might port this cache mechanism to your own config? I still can't reproduce accidentally quit terminal after adding `q` to quit terminal. Or u just tested it?

Currently testing atm.

2023-02-10 10:17 UTC, aarnphm commented
Can confirm caching works.

2023-02-10 10:21 UTC, Jint-lzxy commented
Sorry for the delay. I'm making some minor modifications.

2023-02-10 10:32 UTC, Jint-lzxy requested changes

2023-02-10 10:32 UTC, Jint-lzxy commented on lua/keymap/completion.lua
> +		:with_desc("lsp: Goto type_definition"),
@CharlesChiuGit I would prefer removing these keymaps as they will interfere with `lspsaga`'s `definitions.lua`. _(It will change the state of the servers in some cases, but `lspsaga` obviously wont know this)_

IMO It'll be better to request these features in the upstream repo.

2023-02-10 10:32 UTC, Jint-lzxy commented on lua/modules/configs/tool/telescope.lua
> +	end
These functions can only be used after the plugin is loaded, but we should be able to automatically `require` the plugins after invoking the keymap.

btw I don't think these functions are globally accessable, did I miss something here?

2023-02-10 10:35 UTC, CharlesChiuGit commented on lua/keymap/completion.lua
> +		:with_desc("lsp: Goto type_definition"),
Wow, doesn't know that. Will remove.

2023-02-10 10:38 UTC, CharlesChiuGit commented on lua/modules/configs/tool/telescope.lua
> +	end
ys, this function is globally accessible after this file is loaded. That's why I add `VeryLazy` to telescope's event.

2023-02-10 11:00 UTC, Jint-lzxy commented on lua/modules/configs/tool/telescope.lua
> +	end
> we should be able to automatically `require` the plugins after invoking the keymap. This is what `lazy.nvim` does.

@CharlesChiuGit But not lazy-loading telescope will significantly increase startup time _(before UIEnter)_

2023-02-10 11:02 UTC, Jint-lzxy commented on lua/modules/configs/tool/telescope.lua
> +	end
https://github.com/ayamir/nvimdots/pull/495/commits/9dfc7d7d5c079b57b587273138bef52333aa8cee should fix this.

2023-02-10 11:15 UTC, CharlesChiuGit commented
LGTM

2023-02-10 11:15 UTC, Jint-lzxy approved these changes
LGTM 🍺

@CharlesChiuGit New keymaps (if any) might need to be added to the wiki 👍

2023-02-10 11:17 UTC, merged

2023-02-10 11:17 UTC, CharlesChiuGit commented
The only newly added keymaps are those lsp ones, which is removed now. So I think here's no new keymaps.