fix: remove notify as filetype
ayamir/nvimdots pull request #507
Opened 2023-02-11 09:38 UTC by aarnphm

Fix a regression from 58b4832

Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

2023-02-11 09:39 UTC, CharlesChiuGit commented
Maybe request review from Jint?

2023-02-11 12:05 UTC, Jint-lzxy requested changes

2023-02-11 12:05 UTC, Jint-lzxy commented on lua/core/event.lua
> +		vim.keymap.set("n", "q", "<CMD>close<CR>", { buffer = event.buf, silent = true })
```console
:h nvim_buf_set_keymap

                                                       *nvim_buf_set_keymap()*
nvim_buf_set_keymap({buffer}, {mode}, {lhs}, {rhs}, {*opts})
    Sets a buffer-local |mapping| for the given mode.

    Parameters:  
      • {buffer}  Buffer handle, or 0 for current buffer

    See also:  
        |nvim_set_keymap()|
```

Also `alpha` has filetype 'nofile', pressing `q` inside the dashboard will immediately close it / throw error if it is the last window.

Sorry for the rush review, a kind of busy here

2023-02-11 12:58 UTC, aarnphm commented on lua/core/event.lua
> +		vim.keymap.set("n", "q", "<CMD>close<CR>", { buffer = event.buf, silent = true })
no worries. This shouldn't be the main focus 😄

2023-02-11 12:59 UTC, aarnphm commented on lua/core/event.lua
> +		vim.keymap.set("n", "q", "<CMD>close<CR>", { buffer = event.buf, silent = true })
I also tried nvim_buf_set_keymap but it also raise error.

2023-02-11 13:27 UTC, aarnphm commented on lua/core/event.lua
> +		vim.keymap.set("n", "q", "<CMD>close<CR>", { buffer = event.buf, silent = true })
```suggestion
		vim.api.nvim_buf_set_keymap(event.buf, "n", "q", "<CMD>close<CR>", { silent = true })
```

2023-02-12 01:34 UTC, Jint-lzxy approved these changes

2023-02-12 01:34 UTC, merged