migrate: from efm to null-ls
ayamir/nvimdots pull request #513
Opened 2023-02-13 02:25 UTC by CharlesChiuGit

2023-02-13 02:48 UTC, CharlesChiuGit commented
Do we need to re-implement `FormatToggle` autocmd?

2023-02-13 03:33 UTC, aarnphm commented on lua/modules/configs/completion/mason-tool-installer.lua
> +			-- formatter
quick note on mason-tool-installer. Preferably I like the combination of `mason-null-ls` + null-ls and `mason-lspconfig` + nvim-lspconfig, as these two pairs provide a perfect solution for installing tools and setup their configuration.

Which means we can probably remove this plugin altogether.

2023-02-13 03:39 UTC, CharlesChiuGit commented on lua/modules/configs/completion/mason-tool-installer.lua
> +			-- formatter
That sound reasonable, since `mason-tool-installer` only install formatters for `null-ls` now. Will look into that now.

2023-02-13 03:58 UTC, CharlesChiuGit commented on lua/modules/configs/completion/mason-tool-installer.lua
> +			-- formatter
@aarnphm It seems https://github.com/jay-babu/mason-null-ls.nvim has a much shorter list of supported sources comparing to `mason-tool-installer`. I think I'll stick to `mason-tool-installer` for now.

2023-02-13 12:06 UTC, aarnphm commented on lua/modules/configs/completion/mason-tool-installer.lua
> +			-- formatter
mason-null-ls has a options to follow null-ls.nvim. If you already setup all of the sources for null-ls, then it will automatically install for you. In this way you don't have to context-switch and manage same dependencies at two places.

2023-02-13 16:32 UTC, CharlesChiuGit commented on lua/modules/configs/completion/mason-tool-installer.lua
> +			-- formatter
Ok, it seems `mason-null-ls` has some kind of auto-conversion, so it can install more sources than what's has been stated in it's source table: https://github.com/jay-babu/mason-null-ls.nvim#available-null-ls-sources

2023-02-14 03:26 UTC, ayamir commented on lua/modules/configs/completion/null-ls.lua
> +			extra_args = { "--no-semi", "--single-quote", "--jsx-single-quote" },
No need to add this, because it will respect `.prettierrc.json` automatically.

2023-02-14 07:00 UTC, CharlesChiuGit commented
@aarnphm PTAL

I think it's better to config sources in `null-ls` since some formatters can also be used as lsp, like `markdownlint`. 
I'm not sure what's be setup via `mason-null-ls`' `automatic_setup`, so I think it's better to setup the sources by ourselves separately.

2023-02-15 18:40 UTC, aarnphm approved these changes
LGTM. cc @Jint-lzxy when you have bandwidth.

2023-02-16 01:47 UTC, ayamir commented
`FormatToggle` and `FormatterToggle` haven't been implemented.

2023-02-16 01:50 UTC, ayamir requested changes
`:FormatToggle` and `:FormatterToggle` haven't been implemented.

2023-02-16 05:56 UTC, CharlesChiuGit commented
> `:FormatToggle` and `:FormatterToggle` haven't been implemented.

Ok, I'm on it.

2023-02-16 06:00 UTC, CharlesChiuGit commented
```lua
btn.formatting.clang_format.with({ command = "clang-format -style='{btnasedOnStyle: LLVM, IndentWidth: 4}'" }),
```
I found this line seems to have an error when running `:cheakhealth`.
`- ERROR clang_format: the command "clang-format -style='{btnasedOnStyle: LLVM, IndentWidth: 4}'" is not executable.`
But I'm not familiar with `clang-fornmat`, can someone help me with that?

Here's how `clang-format` configs in `null-ls`:
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/clang_format.lua

2023-02-16 06:07 UTC, ayamir commented
> ```lua
> btn.formatting.clang_format.with({ command = "clang-format -style='{btnasedOnStyle: LLVM, IndentWidth: 4}'" }),
> ```
> 
> I found this line seems to have an error when running `:cheakhealth`. `- ERROR clang_format: the command "clang-format -style='{btnasedOnStyle: LLVM, IndentWidth: 4}'" is not executable.` But I'm not familiar with `clang-fornmat`, can someone help me with that?
> 
> Here's how `clang-format` configs in `null-ls`: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/clang_format.lua
> 
> Maybe use
> 
> ```lua
> btn.formatting.clang_format.with({ args = "-style='{btnasedOnStyle: LLVM, IndentWidth: 4}'" }),
> ```
> 
> instead?

Just because typo of `btnasedOnStyle`, it should be `basedOnStyle` instead.

2023-02-16 06:12 UTC, CharlesChiuGit commented
> Just due to the typo of `btnasedOnStyle`, it should be `BasedOnStyle` instead.

Hmmm, still the same.
`- ERROR clang_format: the command "clang-format -style='{BasedOnStyle: LLVM, IndentWidth: 4}'" is not executable.`

2023-02-16 06:14 UTC, CharlesChiuGit commented
Do I need to install llvm or lldb or actucally use `clang-format` with `BasedOnStyle: LLVM`?

2023-02-16 06:17 UTC, ayamir commented
No need. But I can't see the ERROR after `:checkhealth`. Anyway, maybe there is no need to set it with these argus. Just keep it default also is fine.

2023-02-16 06:18 UTC, CharlesChiuGit commented
got it!

2023-02-16 07:46 UTC, CharlesChiuGit commented
@ayamir Have we tried https://github.com/lukas-reineke/lsp-format.nvim before?
It seems pretty handy.

2023-02-16 09:06 UTC, CharlesChiuGit commented
It seems like the old `formmatting.lua` is more powerful than `ls-format.nvim`. I think I'll tack it back and modify a bit.

2023-02-16 09:09 UTC, ayamir commented
Yes, but we choose to realize the functions by ourselves later.

2023-02-16 09:33 UTC, CharlesChiuGit commented
Do we need to keep the choice to use the actual LSP's formatting ability instead of only use `null-ls` from now on?

2023-02-16 10:59 UTC, CharlesChiuGit commented
In my experiment, `block_list` doesn't seem valid. How do I block a filetype for formatting?

2023-02-16 13:08 UTC, Jint-lzxy commented
> In my experiment, `block_list` doesn't seem valid. How do I block a filetype for formatting?（it doesn't seem to be included in the wiki?

@CharlesChiuGit Yep I plan to review & reimplement `:FormatToggle` and `:FormatterToggle` by the end of this week 👍 Some interaction logic has changed during this migration.

> Do we need to keep the choice to use the actual LSP's formatting ability instead of only use `null-ls` from now on? From a end-user view point, I think it's much easier to only set formatters in `null-ls` config rather than modify `formatting.lua`.
> 
> How do u guys think?

Not sure if I understood this question correctly, but IMHO this choice should be left to users. Some individuals' / organizations' projects would prefer to have formatting support provided by the language server _(especially if they already have a custom configuration file in use)_.

FWIW what we can do is remind users of those conflicting format approaches and ask them to confirm their preferences when encountering this for the first time. We can store these results in a cache file, so that the changes made will be persistent. _(This is also the feature that will be implemented when refactoring `:FormatterToggle`)_

2023-02-16 13:26 UTC, CharlesChiuGit commented
@Jint-lzxy Then i'll just change efm to null-ls and leave everything else untouched. @ayamir how do u think?

2023-02-16 15:10 UTC, CharlesChiuGit commented
> `:FormatToggle` and `:FormatterToggle` haven't been implemented.

@ayamir PTAL

2023-02-16 15:16 UTC, aarnphm approved these changes

2023-02-16 15:17 UTC, CharlesChiuGit commented
side note: I think some of `formatting.lua`'s setting should be prot to `core/settings.lua`. But maybe @Jint-lzxy has already take that into consideration lol

2023-02-16 16:59 UTC, CharlesChiuGit commented
[`2ff5d96` (#513)](https://github.com/ayamir/nvimdots/pull/513/commits/2ff5d9655f8fbede7e6745e5765c575b70c058c4) moves `lsp` and `null-ls` to `core/settings/lua`. Will add this to wiki once merged.

2023-02-17 02:51 UTC, ayamir approved these changes
LGTM 👍

2023-02-17 17:01 UTC, aarnphm commented
Feel free to merge it in when it is gtg

2023-02-18 04:09 UTC, merged