Convert single-mode cables to multi-mode where possible.
ayamir/nvimdots pull request #605
Opened 2023-04-01 04:50 UTC by kang8

Associated with: #603

2023-04-01 09:40 UTC, Jint-lzxy requested changes

2023-04-01 09:40 UTC, Jint-lzxy commented on lua/modules/configs/lang/crates-keymap.lua
Note the minor difference between normal and visual keymaps:
```diff
- require("crates").update_crate()
+ require("crates").update_crates()
                                ^
```

I recommend dropping changes made to this file.

2023-04-03 01:18 UTC, kang8 commented on lua/modules/configs/lang/crates-keymap.lua
Good eyesight! I actually didn't notice this difference.

Fixed.

2023-04-03 10:52 UTC, Jint-lzxy approved these changes
LGTM 🍊

2023-04-03 10:52 UTC, merged