Feat/config for pylsp
ayamir/nvimdots pull request #770
Opened 2023-05-26 16:47 UTC by ayamir

I set the default config for `pylsp` and solved the problem in https://github.com/ayamir/nvimdots/issues/767 by enable `roff` to do lint.

Main config:
1. Use [python-lsp-ruff](https://github.com/python-lsp/python-lsp-ruff) to provide lint function.
2. Use [pylsp-rope](https://github.com/python-rope/pylsp-rope) to provide code refactor function in code action's way as mentioned in https://github.com/ayamir/nvimdots/discussions/708#discussioncomment-5890640.
3. Use [python-lsp-black](https://github.com/python-lsp/python-lsp-black) and [pyls-isort](https://github.com/python-lsp/python-lsp-black) to provide format function.
4. Remove black config in `null-ls`.

Need to discuss:
1. `mason` is not responsible for `pylsp` plugins: https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/server_configurations/pylsp/README.md, so maybe we should manage it in our way, or make users to do it.

2023-05-26 16:48 UTC, ayamir commented
@fecet @CharlesChiuGit

2023-05-26 18:14 UTC, fecet commented
I just started learning about Python's linter and formatter today, so I may not be able to provide any assistance beyond testing. 
What could be the reasons for neodim not supporting it? Ruff support both format and lint. How about using ruff provided by ruff-lsp or null-ls? I've seen https://github.com/CharlesChiuGit/nvimdots.lua/blob/df6576052e3d72f8a76e59457c0101203c634d42/lua/core/settings.lua#L109
configure it that way, if I understand correctly.

2023-05-27 05:52 UTC, ayamir commented
I tend to use `ruff` as plugin of `pylsp` because the dependency is linear.

2023-05-27 09:04 UTC, fecet commented
I have tried this PR and everything works fine! Except I notice two things:

- python-lsp-ruff lint seems too strict, sources like "import but unused" or "line too long" would be considered as "Error".
- ruff's code action "Ruff organize import" will randomly move character:
![image](https://github.com/ayamir/nvimdots/assets/41792945/998bc898-e3b1-4d58-b5bf-73a74fc47c96)

Of course all of them are upstream issues.

2023-05-27 09:54 UTC, ayamir commented
1. I added `F401` and `E501` to ignore.
2. Disable isort because `ruff` can do the same thing.

2023-05-28 10:51 UTC, fecet commented
I think it's better not to include any ignore as default, if anyone found this was annoyed, they could add that in ther `pyproject.toml` or set  `diagnostics_virtual_text` as false (I did this). As there is hope for this issue to be resolved quickly per https://github.com/python-lsp/python-lsp-ruff/issues/36

2023-05-28 17:24 UTC, ayamir commented
OK，we can wait for this.

2023-05-29 07:01 UTC, CharlesChiuGit commented
Agree with @fecet , we can just comment out the `ignore` table.

2023-05-29 07:36 UTC, CharlesChiuGit requested changes

2023-05-29 07:36 UTC, CharlesChiuGit commented on lua/modules/configs/completion/servers/pylsp.lua
> +						"E501",
I think it's better to comment both `E501` and `F401`.

2023-05-29 17:45 UTC, CharlesChiuGit approved these changes

2023-05-30 02:45 UTC, merged