fix: make dap for c/cpp/rust/python works.
ayamir/nvimdots pull request #777
Opened 2023-05-31 07:28 UTC by ayamir

Dap for c/cpp/rust:
We use `lldb-vscode` to debug, but I found that it doesn't work on my arch wsl2 although I have set the `lldb-vscode`'s path to absolute path, ref: https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode
Dap for python:
ref: https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Python

2023-05-31 12:57 UTC, ayamir commented
I'm considering whether add an installation option for dap adapters like `cpptools` and `debugpy` in `install.sh` and `install.ps1`. Now I put the executable path in `~/.local/share/nvim/dap/`.

2023-05-31 13:01 UTC, CharlesChiuGit commented
> Debug for c/cpp/rust can work when using `cpptools` instead.
> 
> I'm considering whether add an installation option for dap adapters like `cpptools` and `debugpy` in `install.sh` and `install.ps1`. Now I put the executable path in `~/.local/share/nvim/dap/`.
> 
> cc @Jint-lzxy @CharlesChiuGit 

I think that's a gd idea, to save some newcomers from confusing.

2023-06-01 02:27 UTC, Groveer commented
> Dap for c/cpp/rust: 用于 c/cpp/rust 的 DAP： We use `lldb-vscode` to debug, but I found that it doesn't work on my arch wsl2 although I have set the `lldb-vscode`'s path to absolute path, ref: https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode 我们使用 `lldb-vscode` 进行调试，但我发现它在我的 arch wsl2 上不起作用，尽管我已将 `lldb-vscode` 的路径设置为绝对路径，参考：https://github.com/mfussenegger/nvim- dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode It needs more test on other platforms. 它需要在其他平台上进行更多测试。 Dap for python:  Dap 为 python： It works now but needs user install `debugpy` manually. 它现在可以工作，但需要用户手动安装 `debugpy` 。 ref: https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Python


`lldb-vscode` works for me, and I do't need absolute path, I use env path.

![图片](https://github.com/ayamir/nvimdots/assets/24505078/cd64b066-f1bf-4008-b9c2-b159a6759bf8)
![图片](https://github.com/ayamir/nvimdots/assets/24505078/c0c5b865-4f65-4ecf-805b-247eaf6f80a4)

2023-06-09 08:42 UTC, ClSlaid commented on lua/modules/configs/tool/dap/dap-lldb.lua
> +local lldb_abspath = vim.fn.exepath("lldb-vscode")
Can we also add codelldb (known as vscode-lldb, not lldb-vscode) for rust?
It has better pretty print support for rust.

2023-06-09 08:44 UTC, ClSlaid commented on lua/modules/configs/tool/dap/dap-lldb.lua
> +local lldb_abspath = vim.fn.exepath("lldb-vscode")
related: https://github.com/ayamir/nvimdots/discussions/551

2023-06-10 08:31 UTC, ayamir commented on lua/modules/configs/tool/dap/dap-lldb.lua
> +local lldb_abspath = vim.fn.exepath("lldb-vscode")
Currently working on my paper. Will impl it when I'm spare.

2023-06-11 17:30 UTC, ayamir commented
![screensht_23-06-12_01:18:07](https://github.com/ayamir/nvimdots/assets/61657399/01b3454a-32c1-4797-8ed8-bbdad879969f)
![screensht_23-06-12_01:28:23](https://github.com/ayamir/nvimdots/assets/61657399/f3d41888-12c4-4d9a-a53b-a4ba9322e372)
![screensht_23-06-12_01:28:54](https://github.com/ayamir/nvimdots/assets/61657399/79b584e3-ce68-4659-a8aa-9482f987ca92)

2023-06-11 22:49 UTC, aarnphm reviewed
The DAP implementation LGTM. I used to use DAP a lot, not anymore. Still cc others to take a look

2023-06-12 02:04 UTC, Groveer commented
LGTM. It works good for me.

2023-06-12 09:06 UTC, CharlesChiuGit approved these changes
LGTM, but I only tested on python

2023-06-12 12:22 UTC, Jint-lzxy commented
Sorry for the delay. Will test on C++, Objective-C, and Swift.

2023-06-12 12:33 UTC, Jint-lzxy requested changes
LGTM, currently working on several cleanups like https://github.com/ayamir/nvimdots/pull/458#issuecomment-1411496895

2023-06-12 12:42 UTC, Jint-lzxy commented
A small change in wording: Executables with LSP-like capabilities are called **"servers"**, while executables having DAP implementations are called **"clients"**.

2023-06-12 13:49 UTC, Jint-lzxy approved these changes
LGTM for `codelldb` and `lldb` 👍

2023-06-12 13:59 UTC, Jint-lzxy commented
https://github.com/ayamir/nvimdots/pull/777/commits/1d9381cba5b3aaba9c66c8965eb16876801dd8e9 implemented a dirty workaround for `utils` (all parameters passed to the adapter should be functions or tables, and they shouldn't be called during setup):

```lua
return setmetatable({}, {
	__index = function(_, key)
		return function()
			return function()
				return M[key]()
			end
		end
	end,
})
```
Not sure if this is the best way to do so 😢

2023-06-13 12:09 UTC, ClSlaid approved these changes

2023-06-13 13:13 UTC, ayamir commented
> all parameters passed to the adapter should be functions or tables, and they shouldn't be called during setup

You are right. Previous implementation has the bug about multi-times prompts asking for exe path.

2023-06-13 14:40 UTC, Jint-lzxy commented
> We use `project.nvim` to change cwd automatically, so is it suitable to use `vim.fn.getcwd()` as default path completion? For example, I have a `Cpp-Practices` git repo to host my cpp code. Now I enter the directory of a leetcode problem and want to debug the executale. So what I needed is current directory path instead of the workspace path provided by `vim.fn.getcwd()`.

https://github.com/ayamir/nvimdots/pull/777/commits/fdb356c1514a4e8167d5ba5b3aaad737d654a537

2023-06-13 15:41 UTC, merged