feat(lspsaga): support v0.3
ayamir/nvimdots pull request #857
Opened 2023-07-11 09:44 UTC by Jint-lzxy

2023-07-11 12:03 UTC, ayamir approved these changes
LGTM 👍

2023-07-12 02:18 UTC, CharlesChiuGit requested changes

2023-07-12 02:18 UTC, CharlesChiuGit commented on lua/modules/configs/completion/lspsaga.lua
> +			show_server_name = false,
I think it would be better to set it to `true`?

2023-07-12 05:48 UTC, Jint-lzxy commented on lua/modules/configs/completion/lspsaga.lua
> +			show_server_name = false,
Agree lol

https://github.com/ayamir/nvimdots/pull/857/commits/4b8b336c0c72e6294f066c5d0b0ef9c9f8e6dbde

2023-07-12 07:03 UTC, CharlesChiuGit approved these changes
LGTM

2023-07-12 07:08 UTC, merged