feat: add `Glance.nvim`
ayamir/nvimdots pull request #920
Opened 2023-08-02 06:54 UTC by Jint-lzxy

https://github.com/ayamir/nvimdots/discussions/494#discussioncomment-6585631

2023-08-02 08:35 UTC, vollowx commented
Maybe a better LSP functions redirecting implementation

```lua
---@diagnostic disable: duplicate-set-field
-- Override LSP handler functions
-- stylua: ignore start
vim.lsp.buf.references = function() glance.open('references') end
vim.lsp.buf.definition = function() glance.open('definitions') end
vim.lsp.buf.type_definition = function() glance.open('type_definitions') end
vim.lsp.buf.implementations = function() glance.open('implementations') end
-- stylua: ignore end
---@diagnostic enable: duplicate-set-field
```

2023-08-02 09:26 UTC, vollowx requested changes
A little fix of appearance.

2023-08-02 09:26 UTC, vollowx commented on lua/modules/configs/completion/glance.lua
> +		zindex = 50,
Catppuccin use darker colors for higher layers.

```lua
theme = {
  mode = 'darken',
},
```

2023-08-02 09:26 UTC, vollowx commented on lua/modules/configs/ui/catppuccin.lua
> +					GlanceWinBarFilename = { fg = cp.subtext1, style = { "bold" } },
Background lost.

```lua
GlanceWinBarFilename = { fg = cp.subtext1, bg = cp.mantle, style = { 'bold' } },
```

2023-08-02 09:26 UTC, vollowx commented on lua/modules/configs/ui/catppuccin.lua
> +					GlanceWinBarFilepath = { fg = cp.subtext0, style = { "italic" } },
```lua
GlanceWinBarFilepath = { fg = cp.subtext0, bg = cp.mantle, style = { 'italic' } },
```

2023-08-02 09:26 UTC, vollowx commented on lua/modules/configs/ui/catppuccin.lua
> +					GlanceWinBarTitle = { fg = cp.teal, style = { "bold" } },
```lua
GlanceWinBarTitle = { fg = cp.teal, bg = cp.crust, style = { 'bold' } },
```

2023-08-02 09:34 UTC, fecet commented
Does glance have https://github.com/nvimdev/lspsaga.nvim/pull/1188 issue?

2023-08-02 09:51 UTC, vollowx commented
> If the definition target are the current buffer, will glance destroy all keymap in the buffer? I fix lspsaga for this [nvimdev/lspsaga.nvim#1188](https://github.com/nvimdev/lspsaga.nvim/pull/1188)?

I have used `glance` for weeks, and didn't mett this issue yet.

2023-08-02 09:55 UTC, fecet commented
That will cause troulbe only in certain case, say you are using a repl should contact to your current buffer or you have some keymap conflict with it, like I set `<CR>` to do incremental selection and this was defined in `peek_definition` in lspsaga.

2023-08-02 13:08 UTC, ayamir commented
One problem is that `glance.nvim` don't have the same ability on lsp goto definition.
I can't goto the definition place when it is defined in other files.

<img width="1263" alt="image" src="https://github.com/ayamir/nvimdots/assets/61657399/cbed9255-c242-48af-8c7c-90399aae20b7">

What's more, the way of overriding lsp handler breaks `Lspsaga goto_definition` defined in `keymap/completion.lua`.

2023-08-02 14:47 UTC, Jint-lzxy commented on lua/modules/configs/completion/glance.lua
> +		zindex = 50,
But IMO it would be better to make this slightly brighter cause it would help distinguish the main window from other floating ones.

2023-08-02 15:06 UTC, Jint-lzxy commented
https://github.com/ayamir/nvimdots/pull/920/commits/313b49a59c217fa093e177f7b85f4201abf7b3fe

2023-08-02 15:23 UTC, Jint-lzxy commented
> If the definition target are the current buffer, will glance destroy all keymap in the buffer?

@fecet I scanned the source code while setting up this plugin, and I don't think it's an issue b/c Glance works quite similarly to our `utils.keymap` module _(i.e., "fixing", not "replacing" the keymap)_. To verify this, `Q` should echo out `MSG` before _and_ after Glance gets opened.
```vim
:noremap <silent> <nowait> <buffer> Q <Cmd>echo 'MSG'<CR>
```

2023-08-02 15:32 UTC, fecet commented
Great, I will test if it works will with my repl later

2023-08-02 17:28 UTC, aarnphm commented on lua/modules/configs/completion/glance.lua
> +	vim.lsp.buf.implementations = function() glance.open("implementations") end
Future proof arg from all buf lsp handler

```suggestion
	vim.lsp.buf.references = function(...) glance.open("references") end
	vim.lsp.buf.definition = function(...) glance.open("definitions") end
	vim.lsp.buf.type_definition = function(...) glance.open("type_definitions") end
	vim.lsp.buf.implementations = function(...) glance.open("implementations") end
```

2023-08-03 02:50 UTC, fecet commented
I originally thought we were going to use glance to replace the peek function of lspsaga, so my previous concerns were irrelevant. But why not?

2023-08-03 02:56 UTC, ayamir commented
> I originally thought we were going to use glance to replace the peek function of lspsaga, so my previous concerns were irrelevant. But why not?

Does it support definition preview?

2023-08-03 02:59 UTC, fecet commented
Doesn't know now but I used glance to preview definition before switching to lspsaga

2023-08-03 11:56 UTC, Jint-lzxy commented
> I originally thought we were going to use glance to replace the peek function of lspsaga, so my previous concerns were irrelevant. But why not?

https://github.com/ayamir/nvimdots/pull/920/commits/3aae05bb04b76888ac94ef8c95439881c777b68f

2023-08-04 02:31 UTC, ayamir approved these changes
LGTM now

2023-08-05 01:53 UTC, aarnphm approved these changes
Works on my end

2023-08-06 07:42 UTC, merged

2023-08-07 09:21 UTC, CharlesChiuGit commented
Works for me too.