feat(completion): use gofumpt to format Go code, run goimports on save
ayamir/nvimdots pull request #996
Opened 2023-09-13 06:39 UTC by cherrot

- Enable `gofumpt` in `gopls` setting since it's widely used in Go community
- Import missing packages via `goimports` on save.

2023-09-13 14:29 UTC, Jint-lzxy requested changes

2023-09-13 14:29 UTC, Jint-lzxy commented on lua/modules/configs/completion/null-ls.lua
> +		btns.formatting.goimports,
Better to move this to `settings["null_ls_deps"]` for automated installs & setups. This table is for sources that are either not registered in `mason-registry` or require some sort of customization.

2023-09-14 04:14 UTC, cherrot commented on lua/modules/configs/completion/null-ls.lua
> +		btns.formatting.goimports,
I also added `gofumpt` to `settings["null_ls_deps"]`  (which is also registered in [null-ls' builtin](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/gofumpt.lua)). 

Could you teach me how to test the automated install feature?  Thanks in advance :)

2023-09-14 12:47 UTC, cherrot commented on lua/modules/configs/completion/null-ls.lua
> +		btns.formatting.goimports,
Cool!

2023-09-15 13:06 UTC, Jint-lzxy commented on lua/modules/configs/completion/servers/gopls.lua
> +			gofumpt = true,
Is it still necessary to set `settings.gofumpt` here? We've already registered that as a null-ls dep (source).

2023-09-16 10:09 UTC, cherrot commented on lua/modules/configs/completion/servers/gopls.lua
> +			gofumpt = true,
You are right. I'd better to leave the minimal change :)

2023-09-17 05:56 UTC, Jint-lzxy approved these changes
LGTM 🍯

2023-09-17 07:53 UTC, ayamir approved these changes

2023-09-17 07:53 UTC, merged

2023-09-20 09:18 UTC, Saafo commented
How to disable these two in user setting? Merging will not remove.

2023-09-20 09:21 UTC, CharlesChiuGit commented
@Saafo take another look at https://github.com/ayamir/nvimdots/wiki/Usage#about-user-overrides-settings-options-events-etc